### ISSUE TITLE
Full Screen splash image in Android

### ISSUE THREAD

**Issue by vukhacbiet** [jonbhanson/flutter_native_splash#129]
I created a splash image at 2400x2400px and in my pubspec.yaml: 
```

flutter_native_splash:
  image: link/to/splash.png
  color: ffffff
  fullscreen: true
  android_gravity: center
  ios: false
```

But when I ran create splash and build for android, everything was not as expected

![Screen Shot 2021-02-09 at 17 01 35](https://user-images.githubusercontent.com/43400653/107347543-832b0380-6af8-11eb-8719-4308071e141f.png)

The image not full screen, I tried to "fill_vertical" "fill_horizontal" but this image not to scale and be stretched

What's expected:

![Screen Shot 2021-02-09 at 17 04 13](https://user-images.githubusercontent.com/43400653/107347871-de5cf600-6af8-11eb-88aa-d438d8f0543e.png)
