### ISSUE TITLE
depends on dev_dependencies from unknown source "flutter_native_splash", version solving failed.

### ISSUE THREAD

**Issue by mellowcello77** [jonbhanson/flutter_native_splash#137]
**Describe the bug**
Because ..... depends on dev_dependencies from unknown source "flutter_native_splash", version solving failed.

**To Reproduce**
dev_dependencies:
  flutter_test:
   sdk: flutter

  dev_dependencies:
    flutter_native_splash: ^0.3.1+1

**Expected behavior**
Load package

I am having trouble adding this package, I have tried everything. Indenting, spaces, with and without the version number. 
Just not coming right. I think there is an issue.

**Comment by mellowcello77** [comment]
`dev_dependencies:
  flutter_test:
   sdk: flutter

  dev_dependencies:
    flutter_native_splash: ^0.3.1+1`

**Comment by mellowcello77** [comment]
`dev_dependencies:
  flutter_test:
   sdk: flutter

  dev_dependencies:
    flutter_native_splash: ^0.3.1+1`

**Comment by mellowcello77** [comment]
```
``dev_dependencies:
  flutter_test:
   sdk: flutter

  dev_dependencies:
    flutter_native_splash: ^0.3.1+1
```
