### ISSUE TITLE
Cannot copy file to 'android/app/src/main/res/drawable-night/background.png', path = 'assets/images/splash.png' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by marcuslma** [jonbhanson/flutter_native_splash#155]
Hi, I'm tried to run the create command, but I'm getting the following error.

**Error**
```
[Android] Updating android/app/src/main/res/drawable/launch_background.xml with splash image path
Unhandled exception:
FileSystemException: Cannot copy file to 'android/app/src/main/res/drawable-night/background.png', path = 'assets/images/splash.png' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.copySync (dart:io/file_impl.dart:340:5)
#2      _createBackground (package:flutter_native_splash/ios.dart:273:37)
#3      _createAndroidSplash (package:flutter_native_splash/android.dart:57:3)
#4      tryCreateSplashByConfig (package:flutter_native_splash/supported_platform.dart:64:5)
#5      tryCreateSplash (package:flutter_native_splash/supported_platform.dart:27:3)
#6      createSplash (package:flutter_native_splash/flutter_native_splash.dart:17:3)
#7      main (file:///Users/marcusmaurmann/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-1.1.5+1/bin/create.dart:5:3)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
pub finished with exit code 255
```
---
**Config**
```
flutter_native_splash:
  background_image: assets/images/splash.png
  background_image_dark: assets/images/splash.png
  web: false
  android_gravity: center
  ios_content_mode: center
```
---
**Version**
```
dev_dependencies:
  flutter_native_splash: ^1.1.5+1
```
