### ISSUE TITLE
On Android full screen phones, a black bar appears at the bottom

### ISSUE THREAD

**Issue by paintingStyle** [jonbhanson/flutter_native_splash#171]
**Describe the bug**
On Android full screen phones, a black bar appears at the bottom

flutter_native_splash: 0.3.2

```
flutter_native_splash: 
  android: true
  ios: true
  # 隐藏通知栏
  fullscreen: true
  # 与 background_image 只能二选一
  color: "#FFFFFF"
  # 必须是png图片
  image: assets/images/common/ic_splash.png
  # scaleToFill、#scaleSpectFit、scaleSpectFill、center、top、bottom、left、right、topLeft、topRight、#bottomLeft或bottomRight。
  ios_content_mode: scaleSpectFill
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  android_gravity: fill
```

**Screenshots**
![image](https://user-images.githubusercontent.com/22866404/117955036-326eb500-b34a-11eb-9d49-d88de4f9bad0.png)

**Device (please complete the following information):**
 - Device:  xiaomi 

**Flutter doctor**
```
rsf@rsfdeMac-mini ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.2.3 20D91 darwin-x64, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)
```
