### ISSUE TITLE
plugin does not create splah logo.

### ISSUE THREAD

**Issue by talhadduman** [jonbhanson/flutter_native_splash#193]
Hey, i've just installed the plugin and set my pubspec.yaml as below
```
flutter_native_splash:
  color: "#00ff00"
  image_path: assets/splash.png
  android: true
  ios: true
```
Unfortunatey, when i start the app, only thing i can see is a colored screen with no logo.
Here's my output of flutter_native_splash:create command.

```
>flutter pub run flutter_native_splash:create
[Android] Updating android/app/src/main/res/drawable/launch_background.xml with splash image path
[Android] Updating android/app/src/main/res/drawable-v21/launch_background.xml with splash image path
[Android] Updating styles.xml with full screen mode setting
[Android] Updating styles.xml with full screen mode setting
[iOS] Updating LaunchScreen.storyboard with width, and height
[iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
[Web] Creating CSS
[Web] Updating index.html

Native splash complete. 👍
Now go finish building something awesome! 💪 You rock! 🤘🤩
```
