### ISSUE TITLE
I can't add a splash page on flutter, can you help me ?

### ISSUE THREAD

**Issue by flomitri** [jonbhanson/flutter_native_splash#195]
I can't create my splash page on flutter cause of this message, do you know what does it means ? Or do you have any solution to solve my problem ?

this is my error message: Could not find package "flutter_native_splash". Did you forget to add a dependency?

this is my code 

```yaml
name: flutter_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.8+4

flutter_native_splash:
    color: "#000000"
    image: assets/ctlogo.png
    android: true
    ios: true

flutter:

  uses-material-design: true

  assets:
   - imageFlutter/
```

**Comment by jonbhanson** [comment]
Did you remember to `flutter pub get` after adding the dependency?  Also, it looks like you have too much space for the entries in the `flutter_native_splash` section.  yaml requires exact spacing, and there should be two spaces before each entry, like this:

```yaml
flutter_native_splash:
  color: "#000000"
  image: assets/ctlogo.png
  android: true
  ios: true
```

Also, please note that the latest version is 1.2.0.
