### ISSUE TITLE
Problem installing 1.2.2

### ISSUE THREAD

**Issue by ElihuJ** [jonbhanson/flutter_native_splash#206]
Cannot install package, I get the following error when running `flutter pub get`

```
[app] flutter pub get
Running "flutter pub get" in app...                        
Because flutter_native_splash >=1.2.2 depends on xml ^5.2.0 which depends on meta ^1.7.0, flutter_native_splash >=1.2.2 requires meta ^1.7.0.


And because every version of flutter from sdk depends on meta 1.3.0, flutter_native_splash >=1.2.2 is incompatible with flutter from sdk.
So, because automate depends on both flutter any from sdk and flutter_native_splash ^1.2.2, version solving failed.
pub get failed (1; So, because automate depends on both flutter any from sdk and flutter_native_splash ^1.2.2, version solving failed.)
exit code 1
```

It's a fresh project so there are not many dependencies:
```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_launcher_icons: "^0.9.2"
  flutter_flavor: ^3.0.3
  flutter_native_splash: ^1.2.2
```

I can install 1.2.1 with no problem
