### ISSUE TITLE
flutter_native_splash color not work on android

### ISSUE THREAD

**Issue by YouSour** [jonbhanson/flutter_native_splash#218]
hi , i got some problem with background color i set `#0071e3` on **Android** it show a white background but **IOS** it works fine , how can i fix it ? thank in advance

`version : flutter_native_splash: ^0.3.2` 
```
flutter_native_splash:
  color: "#0071e3"
  image: "assets/images/splash.png"
  android: true
  ios: true
  fullscreen: true
```

**Problem :**

![splashscreen](https://user-images.githubusercontent.com/9318106/134455646-67e2e515-0ecf-45d2-9dea-ebeedb493c37.gif)
