### ISSUE TITLE
is possible to add gradient color in color?

### ISSUE THREAD

**Issue by hbedford** [jonbhanson/flutter_native_splash#22]
is possible to add gradient color in color?

**Comment by henriquearthur** [comment]
Unfortunately that's not possible.

You could generate an image which contains a gradient and use `fill` property to fill entire screen.

```yaml
flutter_native_splash:
  image: assets/images/image_with_gradient.png
  color: "42a5f5"
  fill: true
```

But the `fill` property only works for Android at the moment.

---

About adding this feature to the package:

In Android a splash screen with gradient could be done using `drawable` but iOS doesn't have anything similar. So in iOS we would have to use an image which contains a gradient and we also need to worry about resolutions.

I believe there are other issues which affects a larger number of people so I will not look into this right now, but I'm leaving it open as a feature request I can take a look in the future.
