### ISSUE TITLE
the splash image is always stretched

### ISSUE THREAD

**Issue by oguzhan2142** [jonbhanson/flutter_native_splash#229]
Splash image always stretching. It should fit in width and overflow vertically. 

wanted:
<img width="393" alt="Ekran Resmi 2021-11-02 11 32 02 kopyası" src="https://user-images.githubusercontent.com/42682090/139813872-b49f9031-a7d5-4b4b-9306-a75235298e25.png">

actual:
<img width="393" alt="Ekran Resmi 2021-11-02 11 32 02" src="https://user-images.githubusercontent.com/42682090/139813895-b3a4543e-2016-46c1-b137-1e0b164caf05.png">

this is how my *flutter_native_splash.yaml*:
```
flutter_native_splash:
  background_image: "assets/images/splash_with_logo.png"

  android: true
  ios: true
  web: false

  android_gravity: bottom

  ios_content_mode: bottom

  fullscreen: false
```
