### ISSUE TITLE
Can't run if I have flutter_launcher_icons

### ISSUE THREAD

**Issue by talamaska** [jonbhanson/flutter_native_splash#239]
**Describe the bug**
Getting weird message in the console after trying to upgrade from flutter_native_splash: 1.1.8+4
for remove and create.
I also have the flutter_launcher_icons plugin which I use to generate my icons

**To Reproduce**
1. flutter_launcher_icons: ^0.9.0 with settings
```
flutter_icons:
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#388e3c"
  adaptive_icon_foreground: "assets/images/icon-foreground.png"
  android: true
  ios: false
```
2. having flutter_native_splash: ^1.1.8+4 installed and run with config 
```
flutter_native_splash:
  image: "assets/images/splash.png"
  color: "388e3c"
  android: true
  android_disable_fullscreen: true
  ios: false
```
3. set the version of this package to 1.3.1
4. run the remove command
5.  See error
```
flutter pub run flutter_native_splash:remove
Could not find a file named "pubspec.yaml" in "C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_launcher_icons-0.9.2"
```

**Expected behavior**
To be able to clean up old splash assets and create new

**Device (please complete the following information):**
 - Device: Emulator
 - OS: Android

**Flutter doctor**
```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1348], locale bg-BG)
    • Flutter version 2.5.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)       
    • Android SDK at C:\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.6)      
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.11.31829.152
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)       

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\zlati.pehlivanov\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (4 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Windows (desktop)                • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1348]
    • Chrome (web)                     • chrome        • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)                       • edge          • web-javascript • Microsoft Edge 95.0.1020.40
```
