### ISSUE TITLE
While removing splash page we get error "Info.plist not found"

### ISSUE THREAD

**Issue by aytunch** [jonbhanson/flutter_native_splash#247]
@jonbhanson Hi.
We have 2 info.plist files under different directories. An when we try to use remove command, it does not work properly even if we already set different info.plist files using `info_plist_files: ` in pubspec.yaml

> File ios/Runner/Info.plist not found.  If you renamed the file, make sure to specify it in the info_plist_files section of your flutter_native_splash configuration.
> pub finished with exit code 1

`ios/Runner/Info.plist` is not supposed to be found anyways because my 2 plists are in different places and are notified in pubspec

**Comment by jonbhanson** [comment]
Can you provide your config?

**Comment by aytunch** [comment]
@jonbhanson 

```
flutter_native_splash:
  web: false
  color: "#fbfbfb"
  image: "assets/images/splash/splash_screen.png"
  color_dark: "#2e2e2e"
  image_dark: "assets/images/splash/splash_screen.png"
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
  info_plist_files:
    - "ios/Runner/Info-Debug.plist"
    - "ios/Runner/Info-Release.plist"
```
