### ISSUE TITLE
Black Statusbar on Splashscreen

### ISSUE THREAD

**Issue by desmeit** [jonbhanson/flutter_native_splash#248]
With Android it starts with a short black statusbar which removes after a second. How can I remove the black statusbar on start?
IOS ist working well.

**Comment by jonbhanson** [comment]
@desmeit please include your flutter doctor output so that I know what version of Android you are running.  Can you supply a video of what happens to help clarify?

**Comment by minh-dai** [comment]
i have the same issue with android

**Comment by alex-myznikov** [comment]
Not sure if my issue is particularly related to this, but after upgrading Flutter to 2.8 I'm also seeing status and system navigation bar black during splash screen on app start even with `<item name="android:windowFullscreen">true</item>`. It seems like maybe Flutter now overrides the defined behaviour...

I've tried running this plugin on default Flutter app with the following:

1. Create a default Flutter app
2. Add flutter_native_splash: 1.3.2
3. Add this to pubspec.yaml
```
flutter_native_splash:
  background_image: assets/background.png
  image: assets/splash.png
  android: true
  android_gravity: center
  ios: false
  web: false
  fullscreen: true
```
4. Run `flutter pub run flutter_native_splash:create`
5. Build app and run

And the result is like:
![Screenshot_1639333952](https://user-images.githubusercontent.com/26327708/145725375-abddcba6-9e15-4f80-9fe8-6ac68523f6d5.png)

The problem disappears after the Flutter app starts and takes control on the system overlays.
