### ISSUE TITLE
Android gravity has no effect

### ISSUE THREAD

**Issue by cycloss** [jonbhanson/flutter_native_splash#250]
I've been battling this for hours now which is quite frustrating. iOS works perfectly when setting the `ios_content_mode` but setting `android_gravity` seems to have no effect on the splash screen.

This is my config:

```yml
flutter_native_splash:
  color: "#F5F8ED"
  image: "assets/splash/beach.png"
  ios_content_mode: scaleAspectFill
  andriod_gravity: fill
  web: false
```
This is what is looks like on android, which is not expected at all. I expected the image to fill the screen.

![image](https://user-images.githubusercontent.com/50776059/146202846-fbaec544-472f-44c9-910b-e2095c8f57ee.png)

At this point I may as well not use this plugin and do everything manually.
