### ISSUE TITLE
android:gravity

### ISSUE THREAD

**Issue by ThierryNapspirit** [jonbhanson/flutter_native_splash#283]
**Describe the bug**

Whatever is the configuration ("android_gravity" in the .yaml file) the package always uses "fill".
I mean the generated file "launch_background.xml" always contains gravity "fill" whatever is specified on the ".yaml" file.

I read your code and it should work....

Package version : 2.0.1+1

Thanks for your job. This is a great package !!

**Configuration (.yaml)**
```

flutter_native_splash:

  # color: "#293a80"
  background_image: assets/images/splashscreen.png
  android_gravity: center
  fullscreen: true

```

**Expected behavior**

Change the "gravity" attribute in the "launch_background.xml" file.

**Device**

 - Device: Android
