### ISSUE TITLE
the background color always black on Dark Mode Android 

### ISSUE THREAD

**Issue by twittergadungan** [jonbhanson/flutter_native_splash#285]
**Describe the bug**
I want my logo and background color to be the same for light and dark mode.  I want a logo on the center with white background.

I have no issue for light mode. but unfortunately there is a black background color even though I have tried to set the background color to be white on dark mode.

here is the video: https://www.youtube.com/watch?v=P_pv96UYg7Q

as you can see, at first, everything is good as expected, there is a logo with white background. but unfortunately after a second, that white background turns  to be black ( it should still be white)

this problem only on Android on Dark Mode

**To Reproduce**
I use flutter_native_splash: ^2.0.1+1

and here is the configuration on my pubspec.yaml

```
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "ffffff"  <---- white
  image: assets/images/logo_for_splash_screen.png
  color_dark: "ffffff" <---- white
  image_dark: assets/images/logo_for_splash_screen.png
```

and then I run

` flutter pub run flutter_native_splash:create`

**Expected behavior**
I expect there is no black background on dark mode, since I set the color to be white both for light mode and dark mode

**Screenshots**
here is the video: https://www.youtube.com/watch?v=P_pv96UYg7Q

**Device **
 - Redmi Note 7
 - Android 10

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-arm, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Additional context**
only on android, everything is good for iOS
