### ISSUE TITLE
Your `pubspec.yaml` file does not contain a `flutter_native_splash` section.

### ISSUE THREAD

**Issue by chrisDK1977** [jonbhanson/flutter_native_splash#291]
I get the error

*** ERROR [flutter_native_splash] ***
NoConfigFoundException
Your `pubspec.yaml` file does not contain a `flutter_native_splash` section.
pub finished with exit code 1

but inside my pubspec.yaml I have:

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  flutter_native_splash:
```

It worked for months and I got the error after my last update.

Adding  flutter_native_splash: ^2.0.2 to the dependencies does not help.
Other commands lile 
flutter pub run flutter_launcher_icons:main 
work....

[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1466], locale de-DE)
    • Flutter version 2.8.1 at C:\SDKs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

**Comment by jonbhanson** [comment]
The section of the pubspec.yaml that you refer to is responsible for including this package in your app.  However, there should also be a [configuration section](https://pub.dev/packages/flutter_native_splash#1-setting-the-splash-screen) in your pubspec.yaml that sets up how this package is configured.  It should look something like this:

```yaml
flutter_native_splash:
  color: "#42a5f5"
  image: assets/splash.png
```

This error indicates that this configuration section cannot be found.
