### ISSUE TITLE
Image is displayed on splash screen on Android 12, but the image doesn't scale.

### ISSUE THREAD

**Issue by MLStoltzenburg** [jonbhanson/flutter_native_splash#303]
**Describe the bug**
Image is displayed on splash screen on Android 12, but the image doesn't scale.

**To Reproduce**

1 - add to dev_dependencies: flutter_native_splash: ^2.1.0

2 - add config to pubspec.yaml
``` yaml
flutter_native_splash:
  color: "#1565C0"
  image: "assets/launcher_icon/splash_full.png"
  color_dark: "#1565C0"
  image_dark: "assets/launcher_icon/splash_full.png"
  android: true
  ios: true
  web: false
  fullscreen: true
  android_12:
    icon_background_color: "#1565C0"
    image: "assets/launcher_icon/splash_full.png"
    image_dark: "assets/launcher_icon/splash_full.png"
    icon_background_color_dark: "#1565C0"
```
	
3 - run flutter clean && flutter pub get && flutter pub run flutter_native_splash:create

4 - Launch app

**Expected behavior**
Show the image scaled in the middle of display.

**Screenshots**
![5477841f-9a1a-41f6-8579-3a69a4b18170](https://user-images.githubusercontent.com/2595026/156947072-5344d9db-98d8-4e3c-8a53-c917bafe5823.jpg)

**Device (please complete the following information):**
 - Device: SM S906E (mobile) • RQCT202J6NL
 - OS: Android 12 (API 31)

**Flutter doctor**
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [version 10.0.22000.527], locale pt-BR)
    • Flutter version 2.10.3 at D:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\tools\Android-SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_SDK_ROOT = D:\tools\Android-SDK
    • Java binary at: D:\tools\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

**Additional context**
I made a workaround manually in #293
I get result below with the workaround.

![7dc42bee-2799-494a-ae07-0abbd207ea24](https://user-images.githubusercontent.com/2595026/156947168-51d7c860-1a36-4b17-b4c8-aabe0ad16457.jpg)
