### ISSUE TITLE
Splashscreen is too small

### ISSUE THREAD

**Issue by erperejildo** [jonbhanson/flutter_native_splash#304]
Probably this is issue was already opened but I can't find any solution.

This is what I see:
![Screenshot_1646693112](https://user-images.githubusercontent.com/5629919/157130880-6d0d3ad3-3294-4766-b6e5-2581bf48a745.png)

Original image (1200x1200):
![icon](https://user-images.githubusercontent.com/5629919/157130943-15b5b16a-090e-477e-a23d-f0e455af0551.png)

Code:
```
flutter_native_splash:
  image: assets/resources/banners/icon.png
  color: '48aa31'
  fill_horizontal: true
```
