### ISSUE TITLE
Image is not showing at all on android 12

### ISSUE THREAD

**Issue by dadav** [jonbhanson/flutter_native_splash#307]
**Describe the bug**
I'm trying to get it working on my pixel 4a phone, but I can't get the image to show up. It's just not there.

**To Reproduce**

Use this config:
```yaml
flutter_native_splash:
  color: "#81c784"
  image: "assets/images/foo.png"
  android: true
  fullscreen: true
  ios: false
  web: false
```

foo.png is the image from #303 

`flutter clean && flutter pub get && flutter pub run flutter_native_splash:create`

**Expected behavior**
The image should be displayed.

**Screenshots**
![foo](https://user-images.githubusercontent.com/33197631/157867051-b65e2afb-01f0-44ed-8ad8-3a4c9aea7d6b.png)

**Device (please complete the following information):**
 - Device: Google Pixel 4a
 - OS: Android 12

**Flutter doctor**
Please paste the results of the `flutter doctor -v` here

```bash
[✓] Flutter (Channel stable, 2.10.3, on Arch Linux 5.16.10-arch1-1, locale de_DE.UTF8)
    • Flutter version 2.10.3 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (vor 9 Tagen), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /opt/android-sdk/Sdk/
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (1 available)
    • Pixel 4a 5G (mobile) • xxxx • android-arm64 • Android 12 (API 31)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by dadav** [comment]
I'm using the package version `2.1.0`

**Comment by dadav** [comment]
Android 7

![Working](https://user-images.githubusercontent.com/33197631/157904221-0fe9f13c-12f4-4ef8-8c09-77227a67eb53.png)

**Comment by dadav** [comment]
I'm using the Nova Launcher on both phones, if this matters...

**Comment by MLStoltzenburg** [comment]
You need to insert android 12 atributes like that.

``` yaml
flutter_native_splash:
  color: "#1565C0"
  image: "assets/launcher_icon/splash_full.png"
  color_dark: "#1565C0"
  image_dark: "assets/launcher_icon/splash_full.png"
  android: true
  ios: true
  web: false
  fullscreen: true
  android_12:
    icon_background_color: "#1565C0"
    image: "assets/launcher_icon/splash_full.png"
    image_dark: "assets/launcher_icon/splash_full.png"
    icon_background_color_dark: "#1565C0"
```

**Comment by martru118** [comment]
I'm facing the same issue. My phone (Samsung Galaxy S10e) recently updated to Android 12, and the image is not showing unlike on Android 11.

I've added Android 12 attributes to my `pubspec.yaml` and applied [the workaround linked here](https://github.com/jonbhanson/flutter_native_splash/issues/293#issuecomment-1059806691). But the image is only shown on my emulator (Google Pixel 2XL on Android 12). My phone still shows the background color without an image.

Also, I'm pretty sure Nova Launcher has nothing to do with this.


**My pubspec:**
```
flutter_native_splash:
  color: "#61B8CC"
  color_dark: "#61B8CC"
  image: assets/launch_image.png
  image_dark: assets/launch_image.png

  ios: false
  web: false
  android12:
    image: assets/launch_image.png
    image_dark: assets/launch_image.png
```

**Comment by martru118** [comment]
**Actually, disregard my point about Nova Launcher**. I found this comment from a StackOverflow thread [discussing the same issue](https://stackoverflow.com/questions/69812590/android-12-splash-screen-icon-not-displaying/69831106#69831106):

> This issue was driving me insane. I followed Googles Guide on how to migrate and the other docs regarding the SplashScreen API. But on my Pixel I use Nova Launcher as desktop and you will never get the icon/images on the splash screen when launching the app from a shortcut or the drawer when using Nova Launcher. And still the same when launching with Android Studio. I only got the icon/images on the splash screen when I launched the app with the Pixel Launcher. So poorly done. – Gimberg Jan 18 at 13:29

I'll try switching back to OneUI and see what happens.

**Comment by dadav** [comment]
I just switched back to the pixel launcher, it's working....So Nova Launcher is the culprit!!

**Comment by jonbhanson** [comment]
Glad you found a solution.  Thanks for the updates.

**Comment by dadav** [comment]
Didn't get any response from the NovaLauncher-Team, but with the latest android 12 working it's finally working!!

**Comment by jonbhanson** [comment]
I will close out this ticket as it sound like the problem has been resolved.

**Comment by naveenbharadwaj19** [comment]
Same issue in pixel 4 emulator (android 12)
```yaml
flutter_native_splash:
  color : "#FFFFFF"
  image: assets/flutter.png
  android: true
  ios: false
  web: false
  android_12:
    image: assets/flutter.png
  ```
  When i launch the app i can see only white screen not the image
