### ISSUE TITLE
android_gravity setting is ignored

### ISSUE THREAD

**Issue by ivanthecrazy** [jonbhanson/flutter_native_splash#335]
**Describe the bug**
android_gravity setting is ignored - no matter what I'll put there, it aways put "fill" into `launch_background.xml`
Splash screen is also stretched when shown.

**To Reproduce**
I have the following in `pubspec.yaml`:

```
flutter_native_splash:
  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
#  color: "#42a5f5"
  background_image: "images/background.png"
  android_gravity: center
```

My splash size is 500x500px.

**Expected behavior**
Run `flutter pub pub run flutter_native_splash:create` and got splash working correctly and not be stretched.

**Device (please complete the following information):**
 - Device: Android Emulator
 - OS: Android 11

**Flutter doctor**

```
[✓] Flutter (Channel stable, 2.10.4, on KDE neon User - 5.24 5.16.0-17.2-liquorix-amd64, locale ru_RU.UTF-8)
    • Flutter version 2.10.4 at /home/ivanthecrazy/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (2 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/ivanthecrazy/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /home/ivanthecrazy/soft/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/ivanthecrazy/soft/android-studio
    • Flutter plugin version 65.2.2
    • Dart plugin version 211.7811
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.65.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 99.0.4844.84

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
