### ISSUE TITLE
The new splash is not update when I using flutter_native_splash

### ISSUE THREAD

**Issue by ManInTheWind** [jonbhanson/flutter_native_splash#338]
**Describe the bug**
I have modified the LauchScreenBoard before,And I using this awesome pkg now. But I found the splash screen is not update.

**To Reproduce**
1. the config of pubspec.yml and flutter clean && flutter pub run ....
```
flutter_native_splash:
  image: assets/images/2.0x/app_icon_white.png
  color: "#38DD8D"
  color_dark: "#161823"
  image_dart: assets/images/2.0x/app_icon_white.png
  android_12:
  fullscreen: true
```
2.the modified LauchScrenn.storyboard
<img width="402" alt="image" src="https://user-images.githubusercontent.com/32859126/163423848-63d4e60f-a4b0-4281-8294-08035831d622.png">

3.my solution
I have try do as Stackflow said:
```
Delete your app from the device
Power down the device
Power up device, install and launch app.
```
its not working.So I build new demo to with this pkg, and work perfect of course.

**Expected behavior**
Hope to perform as new demo do.

**Screenshots**

**Device (please complete the following information):**
 - Device: simulator iPhone 11
 - OS: ios 14

**Flutter doctor**
```
kangkang@MacBook-Pro ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3 21E230 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.1)
[✓] Connected device (2 available)
    ! Error: iPhone 11 is not connected. Xcode will continue when iPhone 11 is
      connected. (code -13)
[!] HTTP Host Availability
    ✗ HTTP host https://maven.google.com/ is not reachable. Reason: An error
      occurred while checking the HTTP host: Operation timed out

! Doctor found issues in 1 category.
```

**Additional context**
What should I do 🤔
