### ISSUE TITLE
Incorrect android_12 check for image_dark

### ISSUE THREAD

**Issue by Hallot** [jonbhanson/flutter_native_splash#347]
**Describe the bug**
Incorrect error message check when trying to set android_12 `image_dark` value.

The following configuration:
```
flutter_native_splash:
  background_image: assets/images/app_splash.png
  background_image_dark: assets/images/app_splash_dark.png
  android_12:
    image: assets/images/app_icon.png
    icon_background_color: #eeeeee
    image_dark: assets/images/app_icon_dark.png
    icon_background_color_dark: #202020
  android: true
  ios: true
  web: false
```

Results in:
"Your `flutter_native_splash` section contains `android_12:icon_background_color_dark` but does not contain a `color_dark` or a `background_image_dark`."

**To Reproduce**
Copy config above and:
`flutter pub run flutter_native_splash:create`

**Expected behavior**
No error is reported.

**Additional context**
Having a look at the code, this sections looks wrong (https://github.com/jonbhanson/flutter_native_splash/blob/master/lib/cli_commands.dart l309):
```
if (android12Config.containsKey('image_dark') &&
        !config.containsKey('color_dark') &&
        !config.containsKey('icon_background_color_dark')) {
      print(
        'Your `flutter_native_splash` section contains '
        '`android_12:icon_background_color_dark` but does not contain a '
        '`color_dark` or a `background_image_dark`.',
      );
      exit(1);
    }
```
It's looking for a `icon_background_color_dark` config in the top level, but there is no such config, it is under the `android_12` namespace. Second, the error message is wrong (most likely copied from the first check just above).  
I am not exactly sure what this check is supposed to ensure though.
