### ISSUE TITLE
Image not displaying on Android 12 Samsung galaxy S21 FE

### ISSUE THREAD

**Issue by Cyansuperfrog** [jonbhanson/flutter_native_splash#361]
**Describe the bug**
On Android 12 Samsung galaxy S21 FE the splash screen image is not displaying. Tested as working on Android 10. 

**To Reproduce**
flutter_native_splash:
  color: "#199ABE"
  android_12:
  image: assets/images/png/splash_logo_android12.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

**Expected behavior**
Expected to see splash image in centre of screen.

**Screenshots**
![screenshot1](https://user-images.githubusercontent.com/90834991/169878852-56f91e22-6123-4e25-bf45-fce9f0dacadd.jpg)

**Device (please complete the following information):**
 - Device: Samsung galaxy S21 FE
 - OS: Android 12

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on Ubuntu 20.04.4 LTS 5.13.0-41-generic, locale en_GB.UTF-8)                                                                                                                             [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.1)
[✓] Android Studio
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Additional context**

**Comment by jonbhanson** [comment]
Did you observer [this note](https://pub.dev/packages/flutter_native_splash#android-12-support) in the readme?

PLEASE NOTE: The splash screen may not appear when you launch the app from Android Studio. However, it should appear when you launch by clicking on the launch icon in Android.

**Comment by Cyansuperfrog** [comment]
Yes did read, the test was direct from the Android device not the emulator.

**Comment by jonbhanson** [comment]
OK, are your indentations correct?  YAML is very picky.  There must be two spaces for each indent level:
```yaml
flutter_native_splash:
  color: "#199ABE"
  android_12:
    image: assets/images/png/splash_logo_android12.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
```

**Comment by Cyansuperfrog** [comment]
I understand, many thanks for your help, I will try this and test tomorrow.
Do not currently have access to the device.

**Comment by jonbhanson** [comment]
> Just curious why this is the case? We've observed this as well and assumed something must be configured incorrectly.

It is related to Android 12, and not this package.  I'm not sure why it happens.

**Comment by Cyansuperfrog** [comment]
Hi, apolgies if I have overlooked something again. Unfortunately I am still getting a coloured screen with no icon on Android 12. Image is 1152px by 1152px with artwork inside 768px by 768px set to png with a transparent background.

**Comment by Cyansuperfrog** [comment]
This is my yaml code:

flutter_native_splash:
  color: "#199ABE"
  image: assets/images/png/splash_logo.png
  android_12:
    image: assets/images/png/splash_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

**Comment by Cyansuperfrog** [comment]
(seems github has removed leading white spaces!)

**Comment by jonbhanson** [comment]
I setup a test config with the following spacing:

```yaml
flutter_native_splash:
  color: "#199ABE"
  image: assets/logo_lockup_flutter_vertical.png
  android_12:
    image: assets/logo_lockup_flutter_vertical.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
```

Then I ran this command:
```
flutter pub run flutter_native_splash:create
```

Then I ran it from Android Studio.  The icon did not show up, as is the case when running Android 12 from Android Studio.  Then, when I launched from the launcher in Android, the icon was there.  

Note that the difference is not between using an emulator vs physical device, the difference is using the debug or run buttons in Android Studio, vs clicking the app icon in the android device to launch the app.
