### ISSUE TITLE
Android 12 use image as branding if branding is not specified

### ISSUE THREAD

**Issue by tonypottera24** [jonbhanson/flutter_native_splash#399]
`flutter_native_splash: ^2.2.3+1`

**To Reproduce**
```
flutter_native_splash:
  color: "#ffffff"
  image: "assets/img/logo/logo.png"
  android_12:
    image: "assets/img/logo/android_splash.png"
    icon_background_color: "#FFFFFF"
```
```
  flutter pub run flutter_native_splash:create
```

**Expected behavior**
No branding when branding image is not specified

**Screenshots**
![Screenshot_1658727129](https://user-images.githubusercontent.com/3013707/180705226-4044e5ad-0f92-4365-ae97-964705f94630.png)

**Device (please complete the following information):**
 - Device: Android simulator
 - OS: API 31
