### ISSUE TITLE
Blank Splashscreen on notification tap

### ISSUE THREAD

**Issue by allanguintu** [jonbhanson/flutter_native_splash#428]
I have a onesignal and flutter_native_splash. Everything is working as expected. If I launch the app via its launcher icon, it shows the splashscreen on both dark mode and normal mode.  But if the app is closed and I tap an incoming notification, the splashscreen logo only shows on darkmode and on normal mode it just shows plain background color (no logo). My logo is just a plain white logo. Only happens on Android 12.

**Configuration**

```
flutter_native_splash:
  image: assets/images/splash.png
  color: "#303030"

  android_12:
    image: assets/images/splash.png
    color: "#303030"
    icon_background_color: "#303030"

  web: false
  fullscreen: true
```

 - Device: Xiaomi 11T Pro
 - OS: MIUI 13
