### ISSUE TITLE
Background image dark mode doesn't work for iOS

### ISSUE THREAD

**Issue by sysint64** [jonbhanson/flutter_native_splash#439]
version: 2.2.11

```yaml
flutter_native_splash:
  background_image_dark: "assets/splash/background_dark.png"
  background_image: "assets/splash/background.png"
  image: "assets/splash/logo.png"
  android: true
  ios: true
  web: false
```

There is a dark image, but it's not attached to dark mode

<img width="555" alt="Screenshot 2022-10-17 at 14 14 41" src="https://user-images.githubusercontent.com/1782848/196163420-16ff2c9d-5df6-4088-a988-9085c727b582.png">

**Content.json**:

```json
{
  "images" : [
    {
      "filename" : "background.png",
      "idiom" : "universal",
      "scale" : "1x"
    },
    {
      "idiom" : "universal",
      "scale" : "2x"
    },
    {
      "idiom" : "universal",
      "scale" : "3x"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
```

Expected **Contens.json**:

```json
{
  "images" : [
    {
      "filename" : "background.png",
      "idiom" : "universal",
      "scale" : "1x"
    },
    {
      "appearances" : [
        {
          "appearance" : "luminosity",
          "value" : "dark"
        }
      ],
      "filename" : "darkbackground.png",
      "idiom" : "universal",
      "scale" : "1x"
    },
    {
      "idiom" : "universal",
      "scale" : "2x"
    },
    {
      "appearances" : [
        {
          "appearance" : "luminosity",
          "value" : "dark"
        }
      ],
      "idiom" : "universal",
      "scale" : "2x"
    },
    {
      "idiom" : "universal",
      "scale" : "3x"
    },
    {
      "appearances" : [
        {
          "appearance" : "luminosity",
          "value" : "dark"
        }
      ],
      "idiom" : "universal",
      "scale" : "3x"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
```
