### ISSUE TITLE
Additional whitespaces added to index.html after call.

### ISSUE THREAD

**Issue by fredrikbaberg** [jonbhanson/flutter_native_splash#451]
**Describe the bug**

Each call of `flutter pub run flutter_native_splash:create` adds two whitespaces after `</picture>` in `index.html`.

**Configuration**

```yaml
flutter_native_splash:
  color: "#42a5f5"
  image: assets/icons/logo.png
```

**Device (please complete the following information):**
 - Device: PC
 - OS: Windows 11
 - Flutter version: 3.3.8
 - `flutter_native_splash` version: 2.2.14

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Run `flutter pub run flutter_native_splash:create`
2. Two whitespaces are added to `web/index.html`, after `</picture>`.

**Screenshots**

**Additional context**
Probably related to #430.
