### ISSUE TITLE
No image is displayed when opening with FCM

### ISSUE THREAD

**Issue by ductdd** [jonbhanson/flutter_native_splash#454]
**Describe the bug**
When opening the application from a notification using FCM while the application is in the terminated state.
Image: not displayed
Color: work

**Configuration**
```yaml
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  branding: assets/images/logo.png
  branding_mode: center
  android_12:
    image: assets/images/logo.png
  ```

**Device:**
 - Device: Samsung Galary S20+
 - OS: Android 13

**Video**
https://user-images.githubusercontent.com/54102426/202892150-ffb6afff-f646-4a2d-97dd-f6d4610833dd.mov

**Cases**
1. Open the app manually: Good
2. Open the app with deeplink: Good
3. Open the app with FCM: NG
