### ISSUE TITLE
background_image for android_12

### ISSUE THREAD

**Issue by yahyaMajdAlamaal** [jonbhanson/flutter_native_splash#456]
I'm trying to add a `background_image` for android 12 and no result

**My Code**
```
flutter_native_splash:
  image: assets/images/logo.png
  background_image: assets/images/splash.png
  android_12:
    image: assets/images/logo.png
    background_image: assets/images/splash.png

  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
```
