### ISSUE TITLE
No Splash Screen on Android 10 & 11

### ISSUE THREAD

**Issue by ErWeiss-LHIND** [jonbhanson/flutter_native_splash#466]
Hello, I can't get a splash screen on Android 11 or 10 wheter on a physical device nor the emulator. The behavior is the same.

When I start the app from Android Studio, no splash screen is shown and it fades directly into the first page of the app. When I then open the app from the drawer after I terminated it, nothing happens. I still see the drawer and after a period of time ( I assume the time the splash screen normally would be shown), again the app opens up directly with the first page.

The behavior is the same on physical device (OnePlus 7/Android 11) and emulators (Google Pixel 6/Android 11, Google Pixel 5/ Android 10)

Android 12 and iOS works just fine.

The flutter_native_splash.yaml

```

flutter_native_splash:

  color: '#004EA8'
 
  image: res/branding.png

 android_12:
  image: res/branding12.png
  icon_background_color: "#004EA8" 
```

**Comment by jonbhanson** [comment]
Indentation is very specific in yaml files.  Your config should look like this:

```yaml
flutter_native_splash:
  color: '#004EA8' 
  image: res/branding.png
  android_12:
    image: res/branding12.png
    icon_background_color: "#004EA8"
```
