### ISSUE TITLE
Not working on real devices (MIUI 13)

### ISSUE THREAD

**Issue by cenyG** [jonbhanson/flutter_native_splash#478]
Hi, this issue but report or feature request, it's just a question.

I have an issue splash screens not working on real devices (in my case - MIUI 13 Android 12).
But actually, it's not about this project, it's in general, works fine in emulator, but not on real devices.
Even default splashscreens (for example default flutter logo on start) not working.

I have such errors:
```
D/hw-ProcessState(18146): Binder ioctl to enable oneway spam detection failed: Invalid argument
E/OpenGLRenderer(18146): fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
E/OpenGLRenderer(18146): fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
```

In my case `backgroundColor` from config works, but logo is not working.
I have such config:
```
flutter_native_splash:
  color: "#ff0000"
  image: assets/images/flutter_logo.png
  android: true
  android_gravity: center
  ios: false
  web: false
  fullscreen: true
  android_12:
    color: "#00ff00"
    image: assets/images/android12splash.png
    icon_background_color: "#0000ff"
```

Don't think there is some bugs in this project, it's seems that it's MIUI Issue, but may be you have some workaround and can help with it.
