### ISSUE TITLE
Splash screen looks dark even when color is set to "#ffffff"

### ISSUE THREAD

**Issue by ExpertKiD** [jonbhanson/flutter_native_splash#485]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

**Describe the bug**

I am setting up the splash screen for android and ios. I am on a dark theme on my device settings. I need the splash screen to be on light theme always even regardless of device theme. However, I get dark theme on device dark mode and light theme on device light mode. The splash screen goes dark or light according to device theme mode. 

I have setup as below.

**Configuration**

**File: flutter_native_splash.yaml**
```
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash/app_icon_with_bg.png

  android_12:
    image: assets/images/splash-v31/app_icon_with_bg_v31_1152.png

  web: false
```

**Device (please complete the following information):**
 - Device: Poco F3 Pro
 - OS: Android 12

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Setup a sample project
2. Setup native splash.
3.  Set above config.
4. Generate the splash.
5. Run the project on android in dark theme.
6. The splash screen should be dark right now even though `color_dark` is not specified.
