### ISSUE TITLE
android splash screen black on open

### ISSUE THREAD

**Issue by arnair** [jonbhanson/flutter_native_splash#493]
**Describe the bug**

On my Samsung 8 plus (android 9) when I open the app first it shows a black screen and after the splash screen

**Configuration**

```yaml
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo_low.png"

flutter_native_splash:
  background_image: "assets/icon/iconback.png"
  color: "#DDFCAC"
  image: "assets/icon/logotrans.png"
  android: true
  ios: true

  android_12:
    color: "#DDFCAC"
    image: "assets/icon/iconback.png"
    icon_background_color: "#DDFCAC"
    image_dark: "assets/icon/logotrans.png"
    icon_background_color_dark: "#DDFCAC"
```

**Device (please complete the following information):**
Samsung 8 plus (android 9)
