### ISSUE TITLE
Splash screen not shown when app launched through intent

### ISSUE THREAD

**Issue by msmartin43** [jonbhanson/flutter_native_splash#496]
I don't think this is necessarily a bug, but its an issue that I am having and would appreciate any help I could get with it.

The splash screen is working perfectly when launched from the application icon, but when my app is launched through an intent via another application the splash screen is never shown.

**Configuration**
```yaml
flutter_native_splash:
  color: "#121212"
  image: lib/assets/images/app_icon_no_background_11.png
  color_dark: "#121212"
  image_dark: lib/assets/images/app_icon_no_background_11.png
  android_screen_orientation: sensorLandscape
  fullscreen: false
  android_12:
    image: lib/assets/images/app_icon_no_background_12.png
    icon_background_color: "#121212"
    image_dark: lib/assets/images/app_icon_no_background_12.png
    icon_background_color_dark: "#121212"
  web: false
```

**Device (please complete the following information):**
 - Device: Samsung S9
 - OS: Android 10
