### ISSUE TITLE
app keeps on showing blue splash screen instead of logo. 

### ISSUE THREAD

**Issue by AbdulHaseeeb** [jonbhanson/flutter_native_splash#505]
pubspec.yaml

```
name: bitbot
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  build_runner: ^2.3.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.3.1
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.9.2
  email_validator: ^2.1.17
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_riverpod: ^2.1.3
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  flutter_tts: ^3.6.3
  go_router: ^6.0.1
  google_fonts: ^3.0.1
  http: ^0.13.5
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  isar_generator: ^3.0.5
  path_provider: ^2.0.11
  salomon_bottom_bar: ^3.3.1
  string_validator: ^0.3.0
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/homepagecarouselimages/
    - assets/images/testimonials/profile/
    - assets/avatars/
    - assets/icons/
    - assets/logo/

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo/botlogo.png

# this is for the launcher icon 
flutter_icons:
  android: true
  image_path: "assets/logo/botlogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  ```

main 

```
main() async {
  //making sure flutter widgets are initialized
  WidgetsFlutterBinding.ensureInitialized();

  FlutterNativeSplash.preserve(
    widgetsBinding: WidgetsFlutterBinding.ensureInitialized(),
  );

  // initializing firebase app
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  HttpOverrides.global = MyHttpOverrides();

  await Isar.open(
    [UserModelSchema],
    inspector: true,
  );
  await IsarUserModelManager.putDefaultModel();
  // await IsarUserModelManager.setIsFirstLaunchToTrue();

  //main app
  runApp(
    ProviderScope(
      child: MaterialApp.router(
        debugShowCheckedModeBanner: false,
        routerConfig: _router,
      ),
    ),
  );

  //removing native splash
  FlutterNativeSplash.remove();

  //<----End---->
}
```

what I've tried
flutter pub run flutter_native_splash:remove
flutter pub run flutter_native_splash:create
