### ISSUE TITLE
Splash screen over than 6s on OPPO A55

### ISSUE THREAD

**Issue by yingming25** [jonbhanson/flutter_native_splash#510]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

**Describe the bug**

Splash screen over than 6s on this package example while i remove manual delay.

**Configuration**
```
flutter_native_splash:
  color: "#e1f5fe"
  image: assets/logo_lockup_flutter_vertical.png
  color_dark: "#042a49"
  image_dark: assets/logo_lockup_flutter_vertical_wht.png
  android_12:
    image: assets/android12splash.png
    color: "#42a5f5"
    icon_background_color: "#eeeeee"
  fullscreen: true
```

**Device (please complete the following information):**
 - Device: OPPO A55
 - OS: Android 12
 - Flutter SDK: 3.3.10 

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. use below code on main.dart:
```dart
import 'package:flutter/material.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

2. Run app by app icon
3. See my problem

**Screenshots**
If applicable, add screenshots to help explain your problem.  If in doubt, attach a screenshot.

**Additional context**

https://user-images.githubusercontent.com/26245479/217463632-0d8b05c8-17ab-4dc7-9920-5a426d818d09.mp4
