### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Broodbakker0106** [jonbhanson/flutter_native_splash#518]
Hello,

i use this code for native_splash.
but the images is not schowing, just default flutter images stil schowing.

`flutter_native_splash:

   color: "#090705"
   images: assets/images/native.png`

**Comment by jonbhanson** [comment]
What platform are you using?  If Android 12+, it requires specific configuration.

**Comment by Broodbakker0106** [comment]
yes i use this code also:
flutter_native_splash:

   color: "#090705"
   images: assets/images/native.png
android_12:
  color: "#090705"
  images: assets/images/native.png

stil no images

**Comment by jonbhanson** [comment]
In YAML, the indenting is very specific.  It looks like your `android_12` parameter is not under the `flutter_native_splash` section.  It should look like this:
```yaml
  color: "#090705"
  images: assets/images/native.png
  android_12:
    color: "#090705"
    images: assets/images/native.png
```
