### ISSUE TITLE
Remove `android:screenOrientation="portrait"` in AndroidManifest.xml

### ISSUE THREAD

**Issue by lsaudon** [jonbhanson/flutter_native_splash#531]
**Describe the bug**

When a launch `flutter pub run flutter_native_splash:create --path=flutter_native_splash.yaml`, `android:screenOrientation="portrait"` is deleted in AndroidManifest.xml

**Configuration**

```yaml
flutter_native_splash:
  color: "#3730A3"
  image: assets/native_splash/logo_splash.png
  android_12:
    color: "#3730A3"
    image: assets/native_splash/logo_splash.png
  fullscreen: true
```
