### ISSUE TITLE
Images having shadow

### ISSUE THREAD

**Issue by jpcarreira** [jonbhanson/flutter_native_splash#538]
I'm experiencing images having a shadow. No matter how much I tweak the `.yaml` file the proceeded asset always have a shadow, for example:

![Screenshot 2023-03-25 at 12 24 10](https://user-images.githubusercontent.com/2743577/227717293-197953d5-3524-4447-8c6a-a196c2981f22.png)

Here's my current config:

```
flutter_native_splash:
  color: '#e5c50e'
  image: assets/splash/splash.png
  android_12:
    image: assets/splash/splash_android12.png
    color: '#e5c50e'
    icon_background_color: '#e5c50e'
  ios: false
  web: false
```

I've tried matching the `color` and `icon_background_color` to see if this would work, but I still get the shadow. Any tips?

Of course, the image I'm using as template **does not have a shadow** so we can rule that out.
