### ISSUE TITLE
black screen on ios

### ISSUE THREAD

**Issue by BrightVan** [jonbhanson/flutter_native_splash#556]
**iOS black screen and should LaunchImage file name should not contains 'Launch'**

**Configuration**

```yaml
flutter_native_splash:
  color: "#ffffff"
  image: assets/logos/logo.png
#  branding: assets/branding-production.png
  color_dark: "#121212"
  image_dark: assets/logos/logo.png
#  branding_dark: assets/branding-production.png

  android_12:
    image: assets/logos/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/logos/logo.png
    icon_background_color_dark: "#121212"

  web: false
```

**Device**
- Flutter 3.10.1,  Using the Impeller rendering backend.
 - Device:ios simulator 14 pro
 - OS: 16.4
 
 **Reproduct**

after `dart run flutter_native_splash:create `,  i reinstall my app, but just the black screen! i search many solution, but not works.
i see someone talled that ' the image name should not contains Launch', i can not belive that, but after have a try, the splash is display.
so maybe the default image name should `SplashImage`, not `LaunchImage`.
but there is still have a 1-2 second black screen before my main page display. i edit my main function like below, but the black screen is still exist.
```dart
void main() async {
  runApp(MaterialApp(
    builder: (context, child) => Scaffold(
      body: Container(color: Colors.green,),
    ),
  ));
}
```
