### ISSUE TITLE
the "fullscreen" switch doesn't work for Android <12v in System.dark mode

### ISSUE THREAD

**Issue by progaman** [jonbhanson/flutter_native_splash#559]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

**Describe the bug**

The "fullscreen" switch doesn't work for Android <12v in System.dark mode.
If I manually add to "android/app/src/main/res/values-**night**/styles.xml" next items, then all is OK

```
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>

```

**Configuration**

```
dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.0
```

```
flutter_native_splash:
  image: assets/images/loglo3_2x2.png
  background_image: assets/images/bg01-1.png
  fullscreen: true
  android_12:
    image: assets/images/loglo3_2x2.png
    color: "#122031"
```

**Device (please complete the following information):**
 - Device: [Pixel 2], but I think, what it will reprodice on any AVD Emulator, with OS < Android-12
 - OS: [API 29]

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Set the config on the example app to 'flutter_native_splash/fullscreen'
2. Run in an emulator configured with 'Settings >Display >Dark theme ON'
3. See what top system icons stay on splash screen when System display in dark mode

**Screenshots**
If applicable, add screenshots to help explain your problem.  If in doubt, attach a screenshot.
![image](https://github.com/jonbhanson/flutter_native_splash/assets/22752489/835abfe8-8b86-468f-9c07-d0c839b4d564)

**Additional context**
