### ISSUE TITLE
 Parser._validate error when running command

### ISSUE THREAD

**Issue by mohadel92** [jonbhanson/flutter_native_splash#564]
i alway get this error when i try to run the command:
```
Unhandled exception:
FormatException: Could not find an option named "dart".
#0      Parser._validate (package:args/src/parser.dart:311:21)
#1      Parser._handleLongOption (package:args/src/parser.dart:300:7)
#2      Parser._parseLongOption (package:args/src/parser.dart:264:12)
#3      Parser.parse (package:args/src/parser.dart:86:11)
#4      ArgParser.parse (package:args/src/arg_parser.dart:334:42)
#5      main (file:///Users/mohammedadelalisorour/.pub-cache/hosted/pub.dev/flutter_native_splash-2.3.1/bin/create.dart:11:29)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:294:33)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

```
flutter_native_splash:

  color: "#212124"
  image: "assets/images/app_square_logo.png"
  color_dark: "#212124"
  #background_image_dark: "assets/dark-background.png"
  image_dark: "assets/images/app_square_logo.png"
  # ios_content_mode: center
  # android: true
  # ios: true
  
  # web: true

```

**Device (please complete the following information):**
 - Device: POCO X3 PRO android  11
