### ISSUE TITLE
[v2.3.1] android < 12 branding image overflows below bottom margin

### ISSUE THREAD

**Issue by gemunet** [jonbhanson/flutter_native_splash#566]
**Describe the bug**

when adding a brand image with "bottom" gravity, it does not look complete and overflows towards the bottom margin, the same does not happen with the "top" gravity.

This behavior only occurs on android below 12. It works perfectly on android 12+ by setting the section "android_12"

I have noticed that the problem occurs when the plugin adds a new property `android:windowDrawsSystemBarBackgrounds` to `true` in `android\app\src\main\res\values\styles.xml`, since changing this to `false` apparently fixes it

**Configuration**

```
flutter_native_splash:
  fullscreen: true
  color: "#ffffff"
  image: "assets/app_icons/android/ic_foreground.png"
  branding: "assets/app_icons/brand_splash.png"
  android_12:
    image: "assets/app_icons/android/android12_logo_splash.png"
    branding: "assets/app_icons/brand_splash.png"
```

> brand_splash.png is 800x320px according to https://developer.android.com/develop/ui/views/launch/splash-screen

**Device (please complete the following information):**
 - Device: Android emulator or phisical device
 - OS: android 11
 
**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. create a new flutter project
2. add the plugin and settings indicated above
3. run the app on android < 12 and see the problem
4. change the windowDrawsSystemBarBackgrounds property to false and try again, to see how it's fixed

**Screenshots**

`android:windowDrawsSystemBarBackgrounds: true` (image looks cropped)
![Snap 2023-06-27 at 00 48 21](https://github.com/jonbhanson/flutter_native_splash/assets/22581144/a394a0a4-e7fc-4507-9214-78891f8959f3)

`android:windowDrawsSystemBarBackgrounds: false` (image looks complete)
![Snap 2023-06-27 at 00 47 36](https://github.com/jonbhanson/flutter_native_splash/assets/22581144/5cda8d7c-5a56-4986-b2f0-0354fb84386e)

**Additional context**

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Versi¢n 10.0.19044.3086], locale es-CL)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.8.5)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.79.2)
[√] Connected device (6 available)
[√] Network resources

```
