### ISSUE TITLE
Splash screen doesn't stretch to full screen

### ISSUE THREAD

**Issue by lucagiordano-visia** [jonbhanson/flutter_native_splash#571]
I have an Huawei P20 Pro with Android10 build in, and the splash screen doesn't stretch to full screen. I would like the notification and bottom bar to be red as well.

```
flutter_native_splash:
  color: "#D5112A"
  image: "lib/assets/splash_image.png"
  fullscreen: true
  web: false

  android_12:
    image: "lib/assets/splash_image.png"
    color: "#D5112A"
```

![Screenshot_20230706_104131_it dapino app dev](https://github.com/jonbhanson/flutter_native_splash/assets/64093474/74f74f39-9360-4d7d-aa98-2b3d768275bf)
