### ISSUE TITLE
Release app: block on splash screen

### ISSUE THREAD

**Issue by Diielle** [jonbhanson/flutter_native_splash#574]
Hi,

I am using the package to have a splash screen on both android and iphone.
This is my code:

```
flutter_native_splash:
  color: "#ffffff"
  image: assets/icona/splashscreen.png
  android_12:
    color: "#ffffff"
    image: assets/icona/splashscreen1152.png
```

Testing with Android Studio everything works correctly. 
When I create the buids and test the apps by downloading them from the stores the app gets stuck on the splash screen.
What do I have to do to fix this?
Thank you
