### ISSUE TITLE
iOS splash icon is too small 

### ISSUE THREAD

**Issue by heshesh2010** [jonbhanson/flutter_native_splash#585]
Hi , in my Figma design I have icon logo 142X72 , and I exported it as 4X , which is dimention 570 X 290 and resolution is  288*288

but in my app the logo is too small , so what is best size to use with iOS to make the icon fit as my Figma ui ? 

my Figma ui splash : 

![Screenshot 2023-08-25 at 2 54 59 AM](https://github.com/jonbhanson/flutter_native_splash/assets/16393042/2d0b7e3e-fa53-4c2c-8527-869e660505ff)

actual splash : 

![Screenshot 2023-08-25 at 3 00 51 AM](https://github.com/jonbhanson/flutter_native_splash/assets/16393042/c1f82804-8555-4766-8962-a130bb0beed7)

-----

also I have another question 

I want to make another splash screen after native screen using my splash widget it must be same as native screen but I'm gonna to add stack widget to show loading spinner in the buttom and other login , but my problem is there is different between logo in native splash size and logo in my custom widget 

here is my code : 

```
Scaffold(
      backgroundColor: mainColor,
      extendBodyBehindAppBar: true,
      extendBody: true,
      body: SafeArea(
        top: false,
        bottom: false,
        child: Center(
          child:
              Image.asset(
            splash_logo, // same image path as android 12 icon image 
          ),
     ),
      ),
    ));

```

```
flutter_native_splash:
  color: "#172E35"

  image_android: assets/images/logo.png
  image_ios: assets/images/logo_ios.png
  android: true
  ios: true
  fullscreen: false
  android_12:
    image: assets/images/splash_logo12.png
    color: "#172E35"
```
