### ISSUE TITLE
Failed to build flutter_native_splash:create

### ISSUE THREAD

**Issue by sauciucrazvan** [jonbhanson/flutter_native_splash#588]
**Describe the bug**

Trying to run the package throws an error saying that it can't find jped_adobe.dart.

**Configuration**

```
flutter_native_splash:
  color: "#F1F1F9"
  image: assets/logo.png
  color_dark: "#333333"
  image_dark: assets/logo.png

  android_12:
    color: "#F1F1F9"
    image: assets/logo.png
    color_dark: "#333333"
    image_dark: assets/logo.png

  web: false
```

**Device (please complete the following information):**
 - Device: PC
 - OS: Windows 11 Pro

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Running the package in the terminal.

**Screenshots**
![image](https://github.com/jonbhanson/flutter_native_splash/assets/108495113/b4dfb758-ed4d-4f61-b9a5-430cabaf82cc)
![image](https://github.com/jonbhanson/flutter_native_splash/assets/108495113/4fb378ea-0028-4f0a-9d90-61f20c35890c)

**Additional context**
I already tried flutter clean and recompiling the app.

***Software versions***
![image](https://github.com/jonbhanson/flutter_native_splash/assets/108495113/3c35087b-42b5-4d56-bf14-5c73a0696ff9)
