### ISSUE TITLE
How to add background_image fit parameter

### ISSUE THREAD

**Issue by lcsvcn** [jonbhanson/flutter_native_splash#589]
How to change **background_image** to **fitHeight**, similar to the **Image.asset** like below:

```
 image: Image.asset(
        'assets/splash.png',
        fit: BoxFit.fitHeight,
      ),
```

Currently, the **background_image** is getting too much strecthed.

**Comment by batuhansavas-yilmaz** [comment]
this is example : 

```
dependencies:
  flutter:
    sdk: flutter




  flutter_native_splash: ^2.3.2
 

flutter_native_splash:
  image: assets/splash_screen/splash_screen.png
  branding: assets/splash_screen/branding_light.png
  color: "#ffffff"
  color_dark: "#000000"
  image_dark: assets/splash_screen/splash_screen_dark.png
  branding_dark: assets/splash_screen/branding_dark.png
  ios: false
  web: false
  android: true
 
  android_12:     
    image: assets/splash_screen/and12/and12_splash.png
    branding: assets/splash_screen/and12/and12branding_light.png
    color: "#ffffff"
    color_dark: "#000000"
    image_dark: assets/splash_screen/and12/and12_splash_dark.png
    branding_dark: assets/splash_screen/and12/and12branding_dark.png

  
 
#dart run flutter_native_splash:create
#dart run flutter_native_splash:remove
```

**Comment by jonbhanson** [comment]
The `background_image` only uses stretch mode.  If you want to use a different mode, use the `image` parameter instead.

**Comment by lcsvcn** [comment]
Yes, I am using image parameter and it is gettings strecthed:

```
flutter_native_splash: ^2.3.2
(...)
flutter_native_splash:
  color: '#8c17a9'
  image: assets/launcher/rounded_corners_icon.png

```
