### ISSUE TITLE
Incompatibility with GDPR's User Messaging Consent dialog (AdMob)

### ISSUE THREAD

**Issue by svprdga** [jonbhanson/flutter_native_splash#590]
**Describe the bug**

If I try to show the AdMob data consent dialog while the splash screen is showing, it is not visible.

**Configuration**

```
flutter_native_splash:
  color: "#ffffff"
  image: "assets/templates/img_splash_light.png"
  color_dark: "#343f44"
  image_dark: "assets/templates/img_splash_dark.png"
  web: false
```

**Device (please complete the following information):**
 - Device: All Android devices I have tested (It doesn't happen on iOS)
 - OS: Reproduced in Android 9, 10 and 12 (not tested in other versions)

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Try to show AdMob's consent dialog while the splash is displayed (https://developers.google.com/admob/flutter/eu-consent)

**Screenshots**
This video demonstrates that the dialogue is there, but it is not displaying as it should:

https://github.com/jonbhanson/flutter_native_splash/assets/43069276/f0acd46b-6c0c-436e-afec-febf873e9ce5

**Additional context**
I have seen this problem in one of the two apps I have tried. In the previous one there was no problem, however I have another one in which this incident occurs.

Apparently the consent management dialog appears but it is below the splash screen, I know this because if I send the app to the list of open apps I can see the dialog flashing, but then when I return that app to the foreground only the splash screen is seen .

Is it possible that there could be some specific setting in Android that could be affecting the display of this dialog?
