### ISSUE TITLE
Google Pixel shows safe area in blue

### ISSUE THREAD

**Issue by rivella50** [jonbhanson/flutter_native_splash#591]
**Describe the bug**

I applied the create call to my current Flutter app. After that when starting the app on my Google Pixel 4a 5G the so far black painted top bar (which hosts the front camera) suddenly is painted in blue, which looks quite strange since now the navigation bar of my app is no more the top bar (see the screenshot below).

**Configuration**
```
flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android_12:
    image: assets/android12splash.png
    color: "#ffffff"
    icon_background_color: "#ffffff"
  ios: false
  web: false
```

**Device (please complete the following information):**
 - Device: Google Pixel 4a 5G
 - OS: Android 14

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Apply the create call
2. Start the app on the mentioned device

**Screenshots**
![Screenshot 2023-09-10 at 14 47 18](https://github.com/jonbhanson/flutter_native_splash/assets/54292/1ce401ff-7641-44b4-b565-b0e32aaf3a31)
