### ISSUE TITLE
android13 not displaying splash screen image properl

### ISSUE THREAD

**Issue by ismanong** [jonbhanson/flutter_native_splash#592]
I've noticed that android13 doesn't display the splash image properly.

This is my configuration:

```yaml
flutter_native_splash.
  background_image: "assets/bundle/launch_background.png"
  android_12:
    # background_image: "assets/bundle/launch_background.png"
  web: true
```

Found that deleting the generated values-v31 and values-night-v31 displays the splash image properly.

However, I later modified values-v31 and values-night-v31 by modifying them and adding the
```xml
<item name="android:windowBackground">@drawable/launch_background</item>
```
It also works fine.

Do we need to update our package to improve it?

![image](https://github.com/jonbhanson/flutter_native_splash/assets/13862699/95051e65-4ab6-48bd-b222-4e7e19900a66)

**Comment by jonbhanson** [comment]
In your example, you have no `image` set in the `android_12` section, so I would not expect the package to display a splash image properly.  In addition, you have a commented `background_image` parameter.  That is not a valid config value in the `android_12` section.

**Comment by felix0324324** [comment]
same error with below code

```
flutter_native_splash:
  background_image: assets/images/white.png
  image: assets/images/icon.png

  android_12:
    image: assets/images/android12_icon.png
    color: "#ffffff"
    icon_background_color: "#ffffff"

  android_gravity: center 
  ios_content_mode: center
  web: false
```
