### ISSUE TITLE
Splash image gets cut always

### ISSUE THREAD

**Issue by lidorcohen12** [jonbhanson/flutter_native_splash#593]
Android Version: 14
Emulated Device: Pixel 7 Pro API 34

I have followed all the steps (multiple times) and used 4 different images with different sizes and resolutions but the image **always** gets cut off by the circle outline border:

![תמונה](https://github.com/jonbhanson/flutter_native_splash/assets/29375106/09238143-0d67-4fc4-961d-07bfd2eff6a6)

This is the yaml file I am using:
```
flutter_native_splash:
  color: "#dcd5cd"
  image: assets/images/ic_launcher.png
  color_dark: "#1b1106"
  image_dark: assets/images/ic_launcher.png

  android_12:
    image: assets/images/ic_launcher.png
    icon_background_color: "#dcd5cd"
    image_dark: assets/images/ic_launcher.png
    icon_background_color_dark: "#1b1106"

  web: false

  android_gravity: fill 
  ios_content_mode: scaleAspectFill
  
  fullscreen: true
```

Tried square, rectangle and circled logos for the splash image - still doesn't seem to work.
Thank you in advance :)
