### ISSUE TITLE
Error running on web: Could not run the JS command removeSplashFromWeb()

### ISSUE THREAD

**Issue by Mazlo-Dev** [jonbhanson/flutter_native_splash#600]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

**Describe the bug**

I've successfully implemented the package and it is working fine, however I see this error everytime I run the app in Chrome:

`Error: PlatformException(error, Exception: Did you forget to run "dart run flutter_native_splash:create"? 
 Could not run the JS command removeSplashFromWeb(), null, null)`

**Configuration**

```
flutter_native_splash:
  color: "#BEC0FF"
  image: assets/logos/splash.png

#  color_dark: "#BEC0FF"
#  image_dark: assets/logos/splash.png
#  branding_dark: assets/logos/splash.png

  android_12:
    image: assets/logos/splash.png
    icon_background_color: "#BEC0FF"
#    image_dark: assets/logos/splash.png
#    icon_background_color_dark: "#BEC0FF"

  web: false
```

I am running `dart run flutter_native_splash:create --path=flutter_native_splash.yaml` because my yaml file is in my lib folder

**Device (please complete the following information):**
 - Device: Macbook Pro / Google Chrome
 - OS: Chrome Version 117.0.5938.149

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Set the config on the example app to the above
2. Run locally via Google Chrome
3. See error

**Screenshots**
<img width="757" alt="Screenshot 2023-10-09 at 8 16 52 PM" src="https://github.com/jonbhanson/flutter_native_splash/assets/117705227/e61e1e5b-d49e-4c55-9e98-d7bd4394fd7b">
<img width="869" alt="Screenshot 2023-10-09 at 8 17 20 PM" src="https://github.com/jonbhanson/flutter_native_splash/assets/117705227/8d08a5dd-66fe-40b8-999d-23b05b5571c3">

**Additional context**
