### ISSUE TITLE
android_gravity not working with android 12 +

### ISSUE THREAD

**Issue by ahmedjedidi** [jonbhanson/flutter_native_splash#615]
**Describe the bug**

when i try to change the position of the splash image to the top it's not working in android >=12

**Configuration**
```yaml
flutter_native_splash:
  image: assets/logo_splash.png
  android_gravity: top

  android_12:
    image: assets/logo_splash_android12.png
    android_gravity: top
```
**Device**
 - Device: Pixel 7
 - OS: API 33
