### ISSUE TITLE
Image being cut

### ISSUE THREAD

**Issue by erperejildo** [jonbhanson/flutter_native_splash#618]
I have followed the rest of issues created but after applying all solutions and can't it working.

I had an image that it was being cut off aroud it so I tried this solution: https://github.com/jonbhanson/flutter_native_splash/issues/593#issuecomment-1732547539
I reduced the image size but after removing/creating it, it was looking exactly the same. So to try, I created a much smaller amount. Same result.

Another issue mentioned adding some padding: https://github.com/jonbhanson/flutter_native_splash/issues/569#issuecomment-1613353357. So I added it to the image, again extra padding. Same result.

I'm not sure what I'm doing wrong because apart from making it smaller I don't see any other rule to follow. Everytime I create a new image I remove the previous one as well.

![image](https://github.com/jonbhanson/flutter_native_splash/assets/5629919/e2dcfced-068b-4bb2-b252-29cdb50ec9dc)

`  flutter_native_splash: ^2.3.5
`
```
flutter_native_splash:
  color: "#dcd5cd"
  image: assets/resources/icon_splash.png

  android_12:
    image: assets/resources/icon_splash.png
    icon_background_color: "#dcd5cd"

  web: false
  android_gravity: fill 
  ios_content_mode: scaleAspectFill
  fullscreen: true
```

@jonbhanson can you point me to some documentation? As mentioned I checked other issues but couldn't resolve this
