### ISSUE TITLE
FullScreen does not work in Android

### ISSUE THREAD

**Issue by jdaduxiacom** [jonbhanson/flutter_native_splash#621]
I try to show fullscreen splash, but I don't know what is the problem.
This is my pubscec.yaml

```yaml
flutter_native_splash:
  color: "#ffffff"
  image: assets/img/splash.png
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  android: true
  ios: true
  fullscreen: true
  android_12:
    color: "#ff0000"
    image: assets/img/splash.png
    background_image: assets/img/splash.png
    android_gravity: fill
    ios_content_mode: scaleAspectFill
    fullscreen: true
```

I have seen this video and test the example and is not working either.

What is wrong?
