### ISSUE TITLE
Android 12+ issues (fullscreen and icon_background_color)

### ISSUE THREAD

**Issue by jibbers42** [jonbhanson/flutter_native_splash#626]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

**Describe the bug**
- `icon_background_color` does not seem to have any effect. My assumption is that this setting should change the color of the circle behind the icon.
- `fullscreen` does not seem to have any effect on Android 12+. On Android 11 the system bars do not show.

**Configuration**
```yaml
flutter_native_splash:
  color: "#42a5f5"
  image: "assets/splash.png"

  android_12:
    color: "#42a5f5"
    icon_background_color: "#111111"

  ios: false
  web: false
  android_gravity: fill
  fullscreen: true
```

**Device (please complete the following information):**
 - Device: emulator v32.1.15-10696886
   OS: Android 13

 - Device: emulator v32.1.15-10696886
   OS: Android 11

- Device: Pixel 3 XL
  OS: Android 12

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Set the config on the example app to config given above.
2. Run using devices listed above.
3. See `fullscreen` have no effect on Android 12+
4. See icon background color remain white on Android 12+.

**Additional context**
The readme links to https://developer.android.com/about/versions/12/features/splash-screen, I'm not sure if I'm supposed to make a changes listed there, but I did add `implementation "androidx.core:core-splashscreen:1.0.0"` to my build.gradle as a test, but it had no effect.
