### ISSUE TITLE
The startup screen on Android 9 is black

### ISSUE THREAD

**Issue by laterdayi** [jonbhanson/flutter_native_splash#629]
**Describe the bug**

The startup screen on Android 9 is black

**Configuration**

```yaml
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/splash.png"
  branding: assets/images/splash_branding.png
  android_12:
    image: "assets/images/splash.png"
    branding: assets/images/splash_branding.png
  web: false

```
