### ISSUE TITLE
The splash screen hasn't changed.

### ISSUE THREAD

**Issue by tempdeltavalue** [jonbhanson/flutter_native_splash#630]
Android studio, Pixel 3a emulator

part of yaml 
```yaml
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  flutter_native_splash: ^2.1.3+1

flutter_native_splash:
  color: "#FAE3E3"
  image: assets/temp.png
  android: true
  ios: true
```

dart run flutter_native_splash:create

logs: 

Building package executable... (1.1s)
Built flutter_native_splash:create.
[Android] Creating default splash images
[Android] Updating launch background(s) with splash image path...
[Android]  - android/app/src/main/res/drawable/launch_background.xml
[Android]  - android/app/src/main/res/drawable-v21/launch_background.xml
[Android] Updating styles...
[Android]  - android/app/src/main/res/values-v31/styles.xml
[Android]  - android/app/src/main/res/values-night-v31/styles.xml
[Android]  - android/app/src/main/res/values/styles.xml
[Android]  - android/app/src/main/res/values-night/styles.xml
[iOS] Creating  images
[iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
Web folder not found, skipping web splash update...
.
✅ Native splash complete.
Now go finish building something awesome! 💪 You rock! 🤘🤩
Like the package? Please give it a 👍 here: https://pub.dev/packages/flutter_native_splash
