### ISSUE TITLE
image gets cropped on android 12

### ISSUE THREAD

**Issue by FarisArmoush** [jonbhanson/flutter_native_splash#632]
**Is your feature request related to a problem? Please describe.**
i added the package and here is the configuration below, the problem is the following, it works great on  iOS devices, but on android the image is cropped into a circle in the middle if the screen.

**Describe the solution you'd like**
my intended behavior is for the image to look on android exactly as it looks on iOS (images below)

**Additional context**
I have tried all of the `android_gravity` properties and absolutely nothing changed.

```
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#ffffff"
  image: assets/splash/splash.png
  image_dark: assets/splash/splash.png
  ios_content_mode: scaleAspectFill
  android_gravity: center_vertical
  ios: true
  android: true
  fullscreen: true
  android_12:
    image: assets/splash/splash.png
    color: "#ffffff"
```
![Simulator Screenshot - iPhone 15 Pro - 2023-12-07 at 16 45 05](https://github.com/jonbhanson/flutter_native_splash/assets/75898233/a0d98caa-1cfd-4ca3-bf73-580a0f19a551)
![Screenshot_1701956654](https://github.com/jonbhanson/flutter_native_splash/assets/75898233/9c091dd7-a1ed-44bf-b77b-7ad411786cd3)
