### ISSUE TITLE
"flutter_lints" is not a valid flutter_native_splash parameter.

### ISSUE THREAD

**Issue by mohsinnaqvi606** [jonbhanson/flutter_native_splash#635]
**Describe the bug**

I am executing this command **dart run flutter_native_splash:create** and getting this response
**The parameter "flutter_lints" was found in your flutter_native_splash config, but "flutter_lints" is not a valid flutter_native_splash parameter.**

**Configuration**

```
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android_12:
    color: "#FFFFFF"
    image: assets/images/logo.png
```

**Screenshots**
![image](https://github.com/jonbhanson/flutter_native_splash/assets/14882412/47907ab7-7d8f-4620-be14-db73d172a6b3)

**Flutter SDK Version**
Flutter 3.16.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9e1c857886 (2 weeks ago) • 2023-11-30 11:51:18 -0600
Engine • revision cf7a9d0800
Tools • Dart 3.2.2 • DevTools 2.28.3
