### ISSUE TITLE
App Launch Problem

### ISSUE THREAD

**Issue by hashemim66110** [jonbhanson/flutter_native_splash#641]
**Describe the bug**

we added flutter_native_splash to our project.
no problem with
``` dart run flutter_native_splash:create ```.
but app dosen't run at all.
```flutter run``` stops after build and install in launching app step ...
we also built app and run on some actual android devices.
couldn't install app on a device with android 9.
using android 11 app installed but after install it was too laggy and slow.
it restart the LDPlayer when we run built apk on this Emulator.

**Configuration**
```yaml
flutter_native_splash:
  background_image: "assets/images/splash-bg.png"
  image: "assets/images/splash-logo.png"
```
**Devices:**
 - Device: [e.g. unknown, android 11]
 - Device: [e.g. LDPlayer, android 9]
 - Device: [e.g. Lenovo Tab3, android 6]

**Additional context**
we tried to set image value as background_image and branding as image. this works kinda fine but when we set background as background_image problem just appear.
