### ISSUE TITLE
Splash icon not showing inside circle shape on Android 11 or lower?

### ISSUE THREAD

**Issue by ntaworking** [jonbhanson/flutter_native_splash#642]
Firstly sorry for my English.
I want to show the splash screen for devices running Android 11 and lower like it does on Android 12.
```
flutter_native_splash:
  color: "#FFFFFF"
  image: lib/assets/images/ic_logo_splash.png
  fullscreen: true

  android_12:
    image: lib/assets/images/ic_logo_splash.png
    color: "#FFFFFF"

```

If I config like above snippet, icon not showing inside circle shape on Android 11 or lower.
How to make it?
