### ISSUE TITLE
Hot restart on web throws exception that cannot be caught

### ISSUE THREAD

**Issue by sunilguptasg** [jonbhanson/flutter_native_splash#644]
**Describe the bug**
main.dart
```
  try {
    FlutterNativeSplash.remove();
  } catch (e) {
    debugPrint(e.toString());
  }
```
Hot restart (web):
```
Error: PlatformException(error, Exception: Did you forget to run "dart run flutter_native_splash:create"? 
 Could not run the JS command removeSplashFromWeb(), null, null)
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3  throw_
packages/flutter/src/services/message_codecs.dart 651:7                      decodeEnvelope
packages/flutter/src/services/platform_channel.dart 322:18                   _invokeMethod
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
```

**Configuration**

```
flutter_native_splash:
  color: "#002f54"
  image: assets/images/splash/tuotr_logo_splash_screen_dark.png
  color_dark: "#002f54"
  image_dark: assets/images/splash/tuotr_logo_splash_screen_dark.png
  #background_image_web: assets/images/splash/tuotr_logo_splash_screen_dark.png
  #background_image_dark_web: assets/images/splash/tuotr_logo_splash_screen_dark.png
  web_image_mode: center
  fullscreen: false
  android: true
  ios: true
  android_12:
    color: "#ffffff"
    color_dark: "#002f54"
    image: assets/images/splash/android12splash.png
    image_dark: assets/images/splash/android12splash.png
```

**Device (please complete the following information):**
- web (Chrome)

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1.  add the FlutterNativeSplash.remove() in main.dart
2. launch Chrome - no issues
3. restart - uncaught exception
