### ISSUE TITLE
[BUG] Flutter Native Splash Show Two Images

### ISSUE THREAD

**Issue by biondiBagasta** [jonbhanson/flutter_native_splash#653]
![native_splash](https://github.com/jonbhanson/flutter_native_splash/assets/75413828/69e9772a-4ce6-4812-965c-d06469cfab94)
My Setting :
```yaml
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#ffffff"
  image: assets/splash-screen.png
  image_dark: assets/splash-screen.png
  branding: assets/splash-screen.png
  branding_dark: assets/splash-screen.png
  android: true
  ios: false
  web: false
  android_gravity: fill
  android_12:
    image: assets/splash-screen.png
    icon_background_color: "#ffffff"
    image_dark: assets/splash-screen.png
    icon_background_color_dark: "#ffffff"
```

**Comment by jonbhanson** [comment]
Try removing the branding parameters.  I think those are causing your problem.

**Comment by Nico3652** [comment]
Hi @jonbhanson, I may have a related issue.

On iOS , i have added a splash, and then I changed the splash ```image:```  and run the ```create``` command again. 
Now, when I launch the app I see the old splash (while 200ms) and very quick the new splash. 

I tried to delete my app and install it again. I also run ```:remove``` command.

Can this use case be linked to this issue ? If not, what can I do to fix this ? 

```
flutter_native_splash:
  color: "#F5EC73"
  color_dark: "#F5EC73"
  image: assets/logo_transparent.png
  image_dark: assets/logo_transparent.png
  web: false
  android: true
```
