### ISSUE TITLE
[Android] app icon not showing on Android 12

### ISSUE THREAD

**Issue by toando0612** [jonbhanson/flutter_native_splash#681]
Describe the bug:

My Issue:
<img width="420" alt="image" src="https://github.com/jonbhanson/flutter_native_splash/assets/33709792/c82b256d-9224-4f73-bf76-07cdefa440f2">

The result that I want:
<img width="378" alt="image" src="https://github.com/jonbhanson/flutter_native_splash/assets/33709792/2f3934c6-b4e5-4a39-a103-fc23c7c8b6d5">

When I run Physical Device and Emulator with Android 12. Splash Screen show, but only have background color. App icon not display.In addition, there were two results if I kill the Application and open it again:
  *Emulator: app icon shown when open again
  *Physical Xiaomi Device: app icon still not display, only see background color as before

-My issue currently happening on (Android 12).
-Android 13 and above working OK.
-Android below 12 working OK.
-Only happen with Android 12

This is my flutter_native_splash.yaml:

```
flutter_native_splash:
  image: assets/images/launch_image.png
  image_dark: assets/images/launch_image.png

  android_12:
    color: "#F14D89"
    color_dark: "#F14D89"
    image: assets/images/app_logo.png
    image_dark: assets/images/app_logo.png

  web: false
  android: true
  ios: false
```
Devices: 
Physical: Xiaomi 11T 12 SP1A, MIUI Global 13.0.5
Emulator: Pixel_6a_API_31
Emulator: Pixel_6a_API_34

To Reproduce
1. Run Application on Emulator/Physical Android 12 devices
2. Kill the app
3. Open app again
