### ISSUE TITLE
the splash screen doesn't show in android devices below android 12 but in android 12 it's work fine

### ISSUE THREAD

**Issue by maysam-ite** [jonbhanson/flutter_native_splash#682]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

**Describe the bug**

the splash screen doesn't show in android devices below android 12 but in android 12 it's work fine

**Configuration**
 flutter_native_splash: ^2.2.8
 
```yaml
flutter_native_splash:
  android: true
  ios: true
  image: "assets/images/newsplash.png"
  color: "#6E429A"
  android_12:
    image: "assets/images/newsplash.png"
    color: "#6E429A"
```  

**Device (please complete the following information):**
 - Device: android's
 - OS: less than android 12

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Set the config on the example app to '...'
2. Run in an emulator configured with '...'
3. See error

**Screenshots**
![photo_2024-03-26_03-28-54](https://github.com/jonbhanson/flutter_native_splash/assets/99141332/4c09cb17-fbf5-40a4-8583-a83b60ee9213)

If applicable, add screenshots to help explain your problem.  If in doubt, attach a screenshot.

**Additional context**
the image doesn't show only the background color
