### ISSUE TITLE
Splash screen not shown properly on android 

### ISSUE THREAD

**Issue by YawarOsman** [jonbhanson/flutter_native_splash#684]
I've added a PNG image(without background) 1152x1152 to the splash and it looks perfect on iOS and web, but on android 12 it won't be shown properly inside the circle.

I looked at https://pub.dev/packages/flutter_native_splash#android-12-support and check all the points but it looks like the problem is different.

I am using the latest version of the package and flutter too.

```
flutter_native_splash:
  image: assets/images/splsh.png

  android_12:
    image: assets/images/splsh.png

```

**Device:**
 - Device: google pixel 3a
 - OS: android 12

**Screenshots**
![Screenshot_1712131931](https://github.com/jonbhanson/flutter_native_splash/assets/68272121/b31b02bb-b30f-4758-95e3-bd336412f635)
