### ISSUE TITLE
using an asset from a package cause splash screen generation to fail

### ISSUE THREAD

**Issue by iapicca** [jonbhanson/flutter_native_splash#687]
### Describe the bug

using an asset from a package (see [docs](https://docs.flutter.dev/ui/assets/assets-and-images#bundling-of-package-assets)), cause splash screen generation to fail

### Configuration

```yaml
dependencies:
# ...
  yakforward_brand:
    git:
      url: https://github.com/yakforward-ou/brand.git
# ...

flutter:
  uses-material-design: true
  assets:
    - packages/yakforward_brand/logo.png

flutter_native_splash:
  color: '#FFFFFF'
  image: packages/yakforward_brand/logo.png
  android: false
  ios: false
  web: true
```

### To Reproduce

- create a package with an asset (image) in the `lib` folder (or use the package above)
- import the assets as in the `configuration` above
- copy the configuration above and run `dart run flutter_native_splash:create`

### logs

```console
dart run flutter_native_splash:create
Building package executable... (1.7s)
Built flutter_native_splash:create.
The file "packages/yakforward_brand/logo.png" set as the parameter "image" was not found.
```

note that the asset is available in app using 

```dart
 Image.asset('packages/yakforward_brand/logo.png');
 ```

### Additional context

<details>
  <summary>flutter doctor</summary>
  
  ```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.3.3/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/francesco/fvm/versions/stable. Consider adding /Users/francesco/fvm/versions/stable/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.88.0)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
  ```
</details>

cc @jonbhanson
