### ISSUE TITLE
Getting strange issue on android 12 showing android app main icon and on 13 showing correct rounded border image

### ISSUE THREAD

**Issue by muhammadarslannasr** [jonbhanson/flutter_native_splash#695]
Getting strange issue on android 12 showing android app main icon and on 13 showing correct rounded border image.

My App contain two images one Square image for App Main icon on android and another with rounded corners for launcher icon.

but when tested it shows rounded corners image on native splash on android 13 and 14 but when check on android 12 shows square image which seems getting from App main icon.

how to fix this or this is default behaviour?

```
flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/png/app_icon.png"
    min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  android_12:
     image: "assets/png/native_splash.png"
  android: true
  ios: false
```
