### ISSUE TITLE
I want to take my image fill on my entire screen but  it's  still on round logo 

### ISSUE THREAD

**Issue by Ntsz2547** [jonbhanson/flutter_native_splash#698]
Hello, I uesd flutter native splash  and i got issue on my projects 

my image is 1152*1152 pixel  

and i want it to fill on my entire screen but it's show on round logo on center of sreen 

here my code
```yaml
flutter_native_splash:
  color: "#42a5f5"
  image: "assets/splash.png"
  android_12:
    image: "assets/splash.png"
    color: "#42a5f5"
  background_image_android: "assets/splash.png"
  background_image_dark_android: "assets/splash.png"
  background_image_ios: "assets/splash.png"
  background_image_dark_ios: "assets/splash.png"
  fullscreen: true
```

my result 
![image](https://github.com/jonbhanson/flutter_native_splash/assets/125390384/c9b69900-7c09-4100-91f7-1f47e46ad29d)

how can i resolve it 

Best regards,
