### ISSUE TITLE
Stuck splash screen at web version.

### ISSUE THREAD

**Issue by rmahfouz** [jonbhanson/flutter_native_splash#702]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

**Describe the bug**

The splash screen is stuck and doesn't load the app. Was working before, but after updating Dart, it stopped transitioning to the app.
It works on android, didn't try on iOs.

**Configuration**

Paste the flutter_native_splash section of your yaml config.
```yaml
flutter_native_splash:
  color: "#ffdb4d"
  #background_image: "assets/background.png"
  image: "lib/assets/Logo TBG.png"
```

**Device (please complete the following information):**
Web (Edge and Chrome).
Android API 32

**To Reproduce**
Steps to reproduce the behavior, using the example app:
Install the plunging with minimal settings as above.
Building or running Web apps doesn't work.

**Screenshots**
https://pocketnephrology.netlify.app/

And FYI, when I try to remove the plugin, the app is stuck at a blank screen with the same background color that I used before.
It seems the remove function doesn't work well for the Web.
