### ISSUE TITLE
Using transparent gif on web flashes white background

### ISSUE THREAD

**Issue by SeriousMonk** [jonbhanson/flutter_native_splash#703]
When running ```dart run flutter_native_splash:create``` command with the following config in ```pubspec.yaml``` file 
```
flutter_native_splash:
  color: "#F48C25"
  image: "assets/animations/egg_jump.gif"
  fullscreen: true
  android_12:
    color: "#F48C25"
    image: "assets/animations/egg_jump.gif"
```

the generated 1x, 2x, 3x, 4x gifs in web/splash/img folder flash a white background if the orginal gif has transparent background.

Original GIF:
![egg_jump](https://github.com/jonbhanson/flutter_native_splash/assets/26068515/e96fa0cd-8566-4270-8a6f-8309f5acb9a8)

Generatet GIF:
![light-4x](https://github.com/jonbhanson/flutter_native_splash/assets/26068515/175b985e-3634-485a-89b3-a2ef67a191f7)

This does not happen if the original gif has a non transparent background.

I am using version ```flutter_native_splash: ^2.4.0``` and the output of ```flutter doctor``` is:
```Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.22631.3593], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.90.0)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
```
