### ISSUE TITLE
 On the Android 13 system, Images cannot be fully displayed

### ISSUE THREAD

**Issue by tilongzs** [jonbhanson/flutter_native_splash#707]
**Describe the bug**

On the Android 13 system, images cannot be fully displayed at low resolution (240 * 240) or high resolution (1152 * 1152).

**Configuration**

```
flutter_native_splash:
  color: "#D8F2FC"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splashAndroid12.png
    color: "#D8F2FC"
    icon_background_color: "#D8F2FC"
```

**Device (please complete the following information):**
 - Device: Pixel 7 emulataor
 - OS: Android 13

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Run Application on Emulator/Physical Android 13 devices
2. Kill the app
3. Open app again

**Screenshots**
![pixel](https://github.com/jonbhanson/flutter_native_splash/assets/18590422/127d413b-e035-491b-949f-890f646bb4ab)

splashAndroid12.png
![splashAndroid12](https://github.com/jonbhanson/flutter_native_splash/assets/18590422/5cd244be-14dd-46ba-9eeb-b1e70639949b)

**Additional context**
Android 11 is working properly.
