### ISSUE TITLE
Android 14 does not display the startup page for the first time

### ISSUE THREAD

**Issue by parshvas1515** [jonbhanson/flutter_native_splash#710]
Hello 
- I'm facing same issue when using native splash and run app in dev mode with opening from android studio or taping from launcher icon all time icons shows .
- When creating relase apk at the very first time it will not show icon it will show only background color and if lunch latter on it will show the splash below is the code snippet for same 

```
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/image/ic_splash_icon_new.png
  color_dark: "#FFFFFF"
  image_dark: assets/image/ic_splash_icon_new.png
  android_gravity: center
  android: true
  ios: true
  image_ios: assets/image/logo.png
  image_dark_ios: assets/image/logo.png
  web: false
  android_12:
    color_dark: "#FFFFFF"
    icon_background_color: "#FFFFFF"
    image: assets/image/ic_splash_icon_new.png
```

_Originally posted by @parshvas1515 in https://github.com/jonbhanson/flutter_native_splash/issues/521#issuecomment-2185725881_
