### ISSUE TITLE
Flutter Native splash getting system theme background color. 

### ISSUE THREAD

**Issue by Abdusamad98** [jonbhanson/flutter_native_splash#711]
I have implemented flutter_native_splash like this order:
```yaml
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  color_dark: "#101924"
  image_dark: assets/images/splash_dark.png
  android: true
  ios: true

  android_12:
    image: assets/images/splash_android_12.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/splash_android_12_dark.png
    icon_background_color_dark: "#101924"
```
    
When I launch app on IOS ,it is getting system dark background color. Theme in app is light.
    
I need that native splash background color match the current theme in my app. Now it is showing system dark mode color.

I am using adaptive_theme package for handling theme logic.
