### ISSUE TITLE
Black screen when entering an application pushed to Google Play Store

### ISSUE THREAD

**Issue by longnh2k1** [jonbhanson/flutter_native_splash#712]
I got a black screen when entering the app on Android 11, but before that the release and debug builds were normal, but when I uploaded the app to the Google Play Store, that error appeared.

Here is my configuration and I didn't do anything else:

```
flutter_native_splash:
  image: "assets/images/splash/LOGO_SPLASH.png"
  background_image: "assets/images/splash/BG_SPLASH_MOBILE.png"
  branding: "assets/images/splash/BRANDING.png"

  android_12:
    color: "#ffffff"
    image: "assets/images/splash/ANDROID12_LOGO_SPLASH.png"
    branding: "assets/images/splash/ANDROID12_BRANDING.png"
  web: false
```

https://github.com/jonbhanson/flutter_native_splash/assets/153590374/1cdfe981-af52-41be-9ec6-7b67101df5c1

Thanks for supporting me.❤️‍🔥

**Comment by jonbhanson** [comment]
If you generate an APK and sideload it onto an Android device, bypassing the Play Store, does the splash screen display correctly?

**Comment by longnh2k1** [comment]
When I build the apk it works fine, only when I push it to Google Play it gets a black screen.

**Comment by dipak-pd** [comment]
I'm also getting black screen on app start

```
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#ffffff"

  android_12:
    color: "#ffffff"
    color_dark: "#ffffff"
```

**Comment by TJMusiitwa** [comment]
Hey @jonbhanson I too have just very recently started to get this same issue mainly on Android. iOS does not raise the issue.

Below is a copy of the logs when running the app on either debug or profile on a physical device

```
✓ Built build/app/outputs/flutter-apk/app-profile.apk (39.7MB)
E/AndroidRuntime(16259): FATAL EXCEPTION: wmshell.splashworker
E/AndroidRuntime(16259): Process: com.android.systemui, PID: 16259
E/AndroidRuntime(16259): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.draw(android.graphics.Canvas)' on a null object reference
E/AndroidRuntime(16259): 	at com.android.wm.shell.startingsurface.SplashscreenIconDrawableFactory$AdaptiveForegroundDrawable.draw(qb/86311146 a982e1cc43cc24626999ad7f15d99b1b844bce33646868d28d69453e901c655d:6)
E/AndroidRuntime(16259): 	at com.android.wm.shell.startingsurface.SplashscreenIconDrawableFactory$ImmobileIconDrawable.preDrawIcon(qb/86311146 a982e1cc43cc24626999ad7f15d99b1b844bce33646868d28d69453e901c655d:31)
E/AndroidRuntime(16259): 	at com.android.wm.shell.startingsurface.SplashscreenIconDrawableFactory$ImmobileIconDrawable$$ExternalSyntheticLambda0.run(qb/86311146 a982e1cc43cc24626999ad7f15d99b1b844bce33646868d28d69453e901c655d:23)
E/AndroidRuntime(16259): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(16259): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(16259): 	at android.os.Looper.loopOnce(Looper.java:230)
E/AndroidRuntime(16259): 	at android.os.Looper.loop(Looper.java:319)
E/AndroidRuntime(16259): 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

My pubspec file definition

```
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: '#FFFFFF'
  image: cu_graphics/icon.png
  android_12:
    color: '#FFFFFF'
```

Let me know what you propose as a solution
