### ISSUE TITLE
White Screen on Subsequent Launches in Emulator After Using flutter_native_splash

### ISSUE THREAD

**Issue by Jalil07** [jonbhanson/flutter_native_splash#713]
Describe the bug:

After integrating the flutter_native_splash package, my app experiences an issue where the screen turns completely white on subsequent launches when run in an emulator. While the widgets are still interactive, they are not visible due to the white screen. This issue is not limited to a single project but affects all Flutter projects after the package has been used. The problem does not occur on physical devices, only in emulators.

Configuration:
Inside pubspec.yaml
```yaml
flutter_native_splash:
  color: "#FBEBD2"
  image: assets/images/splash_logo.png
  android: true
  ios: true

  android_12:
    color: "#FBEBD2"
    image: assets/images/splash_logo.png
```
Device (please complete the following information):

Device: Emulator
OS: Windows 11
Emulator API Levels Tested: 31, 33, 35

To Reproduce

Steps to reproduce the behavior, using the example app:

Set the config on the example app to include flutter_native_splash.
Run in an emulator configured with API levels 31, 33, or 35.
Close the app and reopen it.
Observe the white screen.

Screenshots
in this screen shot i clicked the button for the sliders and it shows up but still all white
![spl](https://github.com/jonbhanson/flutter_native_splash/assets/124510857/a928b6e4-a3d8-485c-b0bf-4fcbe8bde2da)

Additional context

The issue occurs across multiple projects after the package has been integrated.
Testing on a second PC yielded the same results.
Clearing the emulator data or reinstalling the app temporarily resolves the issue, but it reoccurs upon closing and reopening the app.
Physical devices do not exhibit this issue, only emulators.
