### ISSUE TITLE
`flutter_native_splash:create` changes the formatting of `AndroidManifest.xml` and `Info.plist` even if no changes were made

### ISSUE THREAD

**Issue by vanyasem** [jonbhanson/flutter_native_splash#718]
**Describe the bug**

`flutter_native_splash:create` changes the formatting of `AndroidManifest.xml` and `Info.plist` even if no changes were made

**Configuration**

```
flutter_native_splash:
  color: "#696969"
  android_screen_orientation: portrait
  image: assets_splash/splash.png
  android_gravity: center|bottom|clip_horizontal|clip_vertical
  ios_content_mode: scaleAspectFill
  web: false
  android_12:
    color: "#696969"
```

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Apply the splash screen by running `flutter_native_splash:create`
2. Make formatting changes to `AndroidManifest.xml`/`Info.plist`
3. Rerun `flutter_native_splash:create`
4. Observe the fact that `AndroidManifest.xml`/`Info.plist`'s formatting was changed, albeit no changes were made

**Screenshots**
<img width="300" alt="Screenshot 2024-08-05 at 12 05 22" src="https://github.com/user-attachments/assets/1e1c51c7-f40b-49af-ac6f-e03581a1d5b2">

**Additional context**
I'd suggest adding a flag that would instruct `flutter_native_splash` to not make any changes to `AndroidManifest.xml`/`Info.plist`, and only replace the images themselves for cases where only the image needs replacement
