### ISSUE TITLE
Image won't load for android 12 on a Samsung device. 

### ISSUE THREAD

**Issue by WaseekSenju** [jonbhanson/flutter_native_splash#721]
This problem still exists even though I have followed all the guidelines for Android 12.  I suspect that this problem is related to Samsung devices in particular. I got the logo icon on other devices with Android 12+ but it simply didn't work for my Samsung Note10+ which has Android 12.  I was using Nova launcher I tried going back to Samsung's default launcher as well.

**Configuration**

```yaml
flutter_native_splash:
  android: true
  ios: false
  web: false

  color: "FFE500"
  image: "assets/splash-logo-cricle.png"
  branding: "assets/branding.png"

  android_12:
    color: "FFE500"
    image: "assets/splash-logo-cricle.png"
    branding: "assets/branding.png"
```
 - Device: Samsung Note10+
 - OS: Android 12

**Screenshots**

![1723274819021](https://github.com/user-attachments/assets/5acc9f9e-3a51-4667-bcab-3ac07f7b1fe2)
