### ISSUE TITLE
Android 12: dark mode colors not respected when setting to a light color

### ISSUE THREAD

**Issue by Jatoxo** [jonbhanson/flutter_native_splash#730]
**Describe the bug**

When you set 
`color_dark: "#ffffff"`
or 
`icon_background_color_dark: "#ffffff"`
to always have a white splash screen, the option is not respected and a generic dark color is used instead.

**Configuration**

```
flutter_native_splash:
  color: "#ff0000"
  color_dark: "#ff0000"

  image: "assets/mm_logo.png"
  #image_dark: assets/splash-invert.png

  ios: false
  web: false
  android_12:
    image: "assets/logo_splash.png"
    # Splash screen background color.
    color: "#ffffff"
    color_dark: "#ffffff"

    icon_background_color_dark: "#ff0000"
```

**Device (please complete the following information):**
 - Device: Xiami Poco x5 Pro
 - OS: MIUI 14
