### ISSUE TITLE
android12: in dark mode , background color dont response any changes

### ISSUE THREAD

**Issue by Mohamad-Ammis** [jonbhanson/flutter_native_splash#731]
on light mode everything work correcty but when i change to dark mode the splash background color dont accept any changes and still have the default color and dont change to pass color which is "#42a5f5" in my example

**Configuration**
```yaml
flutter_native_splash:
  color: "#ffffff"
  #background_image: "assets/background.png"
  image: assets/images/android14.png
  color_dark: "#42a5f5"
  #background_image_dark: "assets/images/on_boarding.jpg"
  image_dark: assets/images/android14dark.png
  android_12:
    image: assets/images/android14.png
    color: "#ffffff"
    image_dark: assets/images/android14dark.png
    color_dark: "#42a5f5"
  android: true
  ios: true
  web: false
```
 - Device: Redmi Note 10 pro
 - OS: [miui 13 , android 12]
