### ISSUE TITLE
splashscreen       FlutterNativeSplash.remove(); not working .

### ISSUE THREAD

**Issue by AhmedHammad0900** [jonbhanson/flutter_native_splash#740]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

**Describe the bug**

`    FlutterNativeSplash.remove();`

**Configuration**

```yaml
flutter_native_splash:
  color: "#367CFF"
  android: true
  ios: true
  fullscreen: true
  image: assets/splash_images/splashLogo.png

android_12:
  image: assets/splash_images/splashLogo.png
  color: "#367CFF"

```
**Device (please complete the following information):**
 - Device: [Android Tested]

**To Reproduce**
When I do a preserve for splashscreen it remains , but when I try to remove it with remove() it doesn't work

`  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  // FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);`
  
  when I use
  
  `      FlutterNativeSplash.remove();
`
it remains
