### ISSUE TITLE
The Branding Image isn't aligned centered vertically

### ISSUE THREAD

**Issue by niklasbartsch** [jonbhanson/flutter_native_splash#741]
My Branding image of my iOS app is not aligned in center vertically. It is working on web but not on iOS.

This is my configuration:
```
flutter_native_splash:
  color: "#ffffff"
  branding: assets/icons/app_icon_light.png
  branding_mode: center

  color_dark: "#000000"
  branding_dark: assets/icons/app_icon_dark.png

  ios_content_mode: center

```

![Bildschirmfoto 2024-10-11 um 16 38 24](https://github.com/user-attachments/assets/b75152e5-f617-44af-b64f-02b2db3c0715)
