### ISSUE TITLE
Splash screen generated with unexpected results on iOS and Android

### ISSUE THREAD

**Issue by nparoski** [jonbhanson/flutter_native_splash#742]
**Describe the bug**

Flutter logo is shown in center on android and on iOS its all the way on the bottom.

**Expected**

Show my logo in center of the screen on both platforms.

**Configuration**

```
flutter_native_splash:
  color: "#ffffff"
  branding: assets/4x_logo_light.png
  branding_mode: center

  color_dark: "#000000"
  branding_dark: assets/4x_logo_dark.png

  ios_content_mode: center # <-- added on 3-4th run in hope of fixing
  android_gravity: center # <-- added on 3-4th run in hope of fixing

  android_12:
    color: "#ffffff"
    branding: assets/4x_logo_light.png

    color_dark: "#000000"
    branding_dark: assets/4x_logo_dark.png
```
**Device (please complete the following information):**
 - Device: iPhone 15 
 - OS: iOS 17.4
 - Device: Pixel 8 pro API 33
 - OS: android 13

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. configured pubspec.yaml with provided configuration
2. ran `dart run flutter_native_splash:create`
3. issue happens always.

Additionally tried:

1. configure pubspec.yaml
2. dart run flutter_native_splash:remove
3. dart run flutter_native_splash:create

**Screenshots**
![image](https://github.com/user-attachments/assets/c002bca1-d584-4f81-a462-ffdd000b27e9)

**Additional context**
Flutter 3.24.3 • channel stable
Tools • Dart 3.5.3 • DevTools 2.37.3

**Comment by nparoski** [comment]
It was misconfig on my part, branding is not logo `image` should be used. After reconfiguration it works as expected:

```yaml
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/splash_light.png
  image_dark: assets/splash_dark.png

  android_12:
    color: "#ffffff"
    color_dark: "#000000"
    image: assets/splash_light.png
    image_dark: assets/splash_dark.png
```

![image](https://github.com/user-attachments/assets/c4383ca2-562d-41c1-94b2-2f8481eb9a1a)
