### ISSUE TITLE
Splash icon doesn't line up in the middle and goes up on android

### ISSUE THREAD

**Issue by tkddbf7348** [jonbhanson/flutter_native_splash#748]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

**Describe the bug**

The splash icon keeps going up on Android.
I tested android_gravity and it was the same.

My icon is size 940*940,

I also tested the 512 and 1152 sizes.

**Configuration**

```
flutter_native_splash:
  color: "#000000"
  image: assets/images/app_icon_dark_splash.png
  color_dark: "#000000"
  image_dark: assets/images/app_icon_dark_splash.png

  android_12:
    image: assets/images/app_icon_dark_splash.png
    color: "#000000"
    image_dark: assets/images/app_icon_dark_splash.png
    color_dark: "#000000"

  android_gravity: center_vertical
  ios_content_mode: center
```

**Device (please complete the following information):**
 - Device: Samsung Galuxy S 21
 - OS: Android 14, One UI 6.1

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Set the config on the example app to '...'
2. Run in an emulator configured with '...'
3. See error

**Screenshots**
removed `FlutterNativeSplash.remove()` for test.

https://github.com/user-attachments/assets/7cef5d54-78de-4f77-9557-9416e10814d1
![image](https://github.com/user-attachments/assets/b3db8180-ac35-42fa-bdd7-d4cf75967136)
![image](https://github.com/user-attachments/assets/4b422ffc-8a0c-4828-ac48-9e60f8fe4f12)
![app_icon_dark_splash](https://github.com/user-attachments/assets/2f8a0fac-add2-4ccf-8cc9-93a77f4adc3f)

**Additional context**
flutter_native_splash: ^2.4.1

![image](https://github.com/user-attachments/assets/faceaac5-084d-4fa6-bcaa-132d6cbee2bf)
