### ISSUE TITLE
Web doesn't apply branding bottom padding

### ISSUE THREAD

**Issue by ItzNotABug** [jonbhanson/flutter_native_splash#765]
**Describe the bug**

1. Used -
`branding_bottom_padding: 24`

2. Ran -
`dart run flutter_native_splash:create`

Open the app on Web (chrome) , branding bottom padding is not applied.
Here's the output css from the `index.html` - 
```css
.bottom {
  position: absolute;
  bottom: 0;
  left: 50%;
  -ms-transform: translate(-50%, 0);
  transform: translate(-50%, 0);
}
```

**Configuration**

```yaml
flutter_native_splash:
  color: "#EDEDF0"
  color_dark: "#19191D"
  image: assets/splash-logo.png

  # branding
  branding_bottom_padding: 24
  branding: assets/branding-light.png
  branding_dark: assets/branding-dark.png

  web: true
  ios: true
  android: true
  fullscreen: true
```

**Device (please complete the following information):**
 - Chrome

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. `branding_bottom_padding: 24`
2. `dart run flutter_native_splash:create`
3. Run on Chrome

**Additional context**
N/A.
