### ISSUE TITLE
Splash Screen Stuck In some Cases

### ISSUE THREAD

**Issue by Samrakk** [jonbhanson/flutter_native_splash#771]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

**Describe the bug**

It is stuck in Native Splash screen.
**Configuration**

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.4

# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/images/splash12.png

  android_12:
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#FFFFFF"
    image: assets/images/splash12.png

  web: false

**Device (please complete the following information):**
 - Device: [e.g. iPhone16, iPhone15]
 - OS: [e.g. iOS8.1,  iOS8.2, iOS8.3,]

**To Reproduce**
Steps to reproduce the behavior, using the example app:
I can catch this issue by using SmarLook. 
Some customers are stuck in Splash Screen Directly.

**Screenshots**

![Image](https://github.com/user-attachments/assets/6cf2e8a6-ba37-4948-8e48-be026d541b2f)
![Image](https://github.com/user-attachments/assets/e8808965-8311-49a5-bc87-d696f55dbe58)

**Additional context**

**Comment by jonbhanson** [comment]
Are you calling `FlutterNativeSplash.remove();`?

If so, when the splash screen is stuck, it generally means something is hanging with the initialization of the app.  You can test this by bypassing your app and returning a blank app instead and see if the splash screen still hangs.

**Comment by Samrakk** [comment]
Hello Jon, i am aware of all these things i released new version last week.

**Comment by jonbhanson** [comment]
If you list this package in `dev_dependencies`, you will not be able to use `FlutterNativeSplash.remove();` in release.

**Comment by Samrakk** [comment]
Hello Jon, ı sent you my codes could you tell me is there anything wrong ?

[image: Screenshot 2025-02-17 at 09.48.06.png]


I think you mean here. I can change it.

This is my main.dart, I added 2 FlutterNativeSplash. Remove () from the
main.dart Do you think they are okay?

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await initializeApp(); // Avoid excessive delays
  FlutterNativeSplash.remove(); // Added for remove
  await Firebase.initializeApp();

  try {
    // Set the background messaging handler early on, as a named
top-level function
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
    print('Background message handler registered.');
  } catch (e) {
    ServerLogError.add('Error Background message handler: ', e);
  }

  try {
    // Enable Crashlytics Monitoring
    FirebaseCrashlytics.instance.setCrashlyticsCollectionEnabled(true);

    // Enable Performance Monitoring
    FirebasePerformance.instance.setPerformanceCollectionEnabled(true);
  } catch (e) {
    ServerLogError.add('Error Firebase Services Crash Detected: ', e);
  }

  try {
    // Fix Error: CERTIFICATE_VERIFY_FAILED
    HttpOverrides.global = MyHttpOverrides();
  } catch (e) {
    ServerLogError.add('Error HttpOverrides: ', e);
  }

  Locator.setupLocator(); //TicketNetwork API start

  await LocalData.instance.init();
  await AppConfig.instance.init();
  await Api.instance.init();

  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  AppColors.init(appColors: getAppColors());
  // Pass all uncaught errors from the framework to Crashlytics.
  FlutterError.onError = (FlutterErrorDetails details) {
    print('details_library :${details.library}');
    print('details_library :${details.exception.toString()}');
    print('details_library :${details.stack.toString()}');
    switch (details.library) {
      //excludes errors
      case 'image resource service':
      case 'SVG':
      case 'Flutter test framework':
        return;
    }
    FirebaseCrashlytics.instance.recordFlutterFatalError(details);
  };

  locator<AnalyticsService>().logAppOpen();


  WidgetsBinding.instance.addPostFrameCallback((_) {. // Added for remove
    FlutterNativeSplash.remove();
    print("First frame rendered. Splash screen should be gone.");
  });

**Comment by jonbhanson** [comment]
```yaml
dependencies:
  flutter_native_splash: ^2.4.4  #place the dependency for this package here instead of below.
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  # flutter_native_splash: ^2.4.4. #this is in the wrong place.  Remove it from here.

# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/images/splash12.png

  android_12:
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#FFFFFF"
    image: assets/images/splash12.png

  web: false
```
