### ISSUE TITLE
image does not appear when you start the application with android 12 api 32

### ISSUE THREAD

**Issue by pedroprenhaca** [jonbhanson/flutter_native_splash#774]
**Describe the bug**

The image does not appear when you start the application from scratch, however when it is started using the application icon the image appears normally, this only happens when I use the Pixel 8 with Android 12 API 32, versions below 12 and above 12 the image appears normally.

**Configuration**

```yaml
flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#0F80B9"
  image: assets/splash/seo_mercato_1152_1152.png
  image_dark: assets/splash/seo_mercato_1152_1152_dark.png
  color_dark: "#121212"

  android_12:
    color: "#0F80B9"
    image: assets/splash/seo_mercato_1152_1152.png
    image_dark: assets/splash/seo_mercato_1152_1152_dark.png
    color_dark: "#121212"
```

**Device (please complete the following information):**

**Screenshots**

starting first time

![Image](https://github.com/user-attachments/assets/f37ab6b8-7cd3-4c1c-b21e-5b8d2bd5b245)

after already started

![Image](https://github.com/user-attachments/assets/7d737569-979f-48c6-baf6-d3662de1daa8)

**Additional context**
